### ISSUE TITLE
Small issues in chapter research compendia

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#1003]
### Summary

- Link for subsections does not work as I expected. See screenshot from https://the-turing-way.netlify.com/research_compendia/research_compendia.html:

![image](https://user-images.githubusercontent.com/14146757/78155599-f5917880-743d-11ea-8e63-bdb3547ea061.png)
- A few typos

### What needs to be done?

- [x] Can anyone tell me how to do links to subsections of the chapter? :grimacing: 
- [x] Fix typos (I can do that)

### Who can help?

People who know stuff about git books and links. :book: 

---

### Updates

- Created PR #1004 
- Please comment about the link stuff below :clap:

**Comment by growupboron** [comment]
@HeidiSeibold Is this issue still applicable?

**Comment by HeidiSeibold** [comment]
Maybe the link problem is because we are closing two round brackets? One for the link and one for the side note. :thinking:

**Comment by growupboron** [comment]
> Maybe the link problem is because we are closing two round brackets? One for the link and one for the side note. thinking

@HeidiSeibold, As you can see in the [commit](https://github.com/alan-turing-institute/the-turing-way/pull/1077/commits/109c10e006047070f5f0096082051d3059777e82) of the PR #1077, there was small mistake of missing ```/``` before specifying the internal link route. Since ```/``` wasn't mentioned, it was taking the current directory of the markdown file ```research_compendia``` and appending the rest of the link forward. A simple addition of ```/``` fixes the issue. I hope, this cleared any confusion.

**Comment by HeidiSeibold** [comment]
Nice, thanks for your help @growupboron :clap:

**Comment by growupboron** [comment]
@HeidiSeibold Happy to help, much obliged. Me being a new contributor, would like to ask if you're writing/editing any particular chapter of the book, I'll be glad to help.
Regards.

**Comment by HeidiSeibold** [comment]
Can be closed as it was fixe by PR #1077
