### ISSUE TITLE
Updating Contributor list

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1054]
### Summary

* Make sure that anyone who makes any contribution to the GitHub (issue, PR, commit, review) gets added to the contributors list

### What needs to be done?

- [ ] Create CL tool to check GitHub history and compare with all contributors file (@adswa  is working on it)
- [ ] Create a system for the contributors to come and update their info
- [ ] Create an accountability format (one contributor checks with one another member)

### Who can help?

* anyone interested in this topic

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by sgibson91** [comment]
FYI, the all-contributors CLI has a [check function](https://allcontributors.org/docs/en/cli/usage#all-contributors-check) which @adswa may find helpful :)

**Comment by adswa** [comment]
oh, I didn't know! That would make most of what that tool is superfluous :) Has anyone ever run it?

**Comment by sgibson91** [comment]
I have on another project. Your output is much prettier and informative as you tell us what the person has done! The cli just outputs a list of people 😊

**Comment by adswa** [comment]
@sgibson91 because we briefly chatted about output formatting with emojis: I stumbled across https://github.com/willmcgugan/rich, and I think it will make formatting for this tool not only easier but also way prettier! I'll switch to using that :relaxed:

**Comment by sgibson91** [comment]
Ohhhh, that looks so nice! 😻

**Comment by EstherPlomp** [comment]
Hello from 2023 all! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
