### ISSUE TITLE
Broken link of image 

### ISSUE THREAD

**Issue by Yash-Varshney** [alan-turing-institute/the-turing-way#1079]
### Bug description
In the chapter `Collaborating Github' under [checklist_bibliography](book/content/collaborating_github/4/checklist_bibliography.md) section, the image link provided is broken ( results in Error 404).

#### Expected behavior
On clicking the link it should give an image of [Community Profile](https://github.com/alan-turing-institute/the-turing-way/community)

### How to reproduce
Updating the broken link with the desired image should work.

- Browser:

- [x]  *Chromre*
- [ ]  *Firefox*

**Comment by KirstieJane** [comment]
This looks like a great first issue @Yash-Varshney! Would you like to work on it?

**Comment by Yash-Varshney** [comment]
Thanks, @KirstieJane . I would definitely love to work on this.

**Comment by iiitmjay** [comment]
@KirstieJane , @malvikasharan  As far as this issue is concerned, I had already looked into the source code of that file and found that the link which has been put up on the image is not one of the incorrected path as the photograph community_profile_github.png  is not found and meanwhile /assets do not contain folder /figures... and that's why the problem occurs.
And it is to be noted that figures folder is in /book/content/ ... but I failed to find the same photo there also.

**Comment by iiitmjay** [comment]
~~ is not one of the corrected path ~~


> @KirstieJane , @malvikasharan As far as this issue is concerned, I had already looked into the source code of that file and found that the link which has been put up on the image is ~~not~~ one of the incorrected path as the photograph community_profile_github.png is not found and meanwhile /assets do not contain folder /figures... and that's why the problem occurs.
> And it is to be noted that figures folder is in /book/content/ ... but I failed to find the same photo there also.

some minor mistakes

**Comment by malvikasharan** [comment]
Hi @iiitmjay, this is what is addressed by @Yash-Varshney in the issue. I think Yash is working on this issue.

**Comment by malvikasharan** [comment]
Hi @Yash-Varshney, thank you for fixing this issue. Please go ahead and merge the PR when you are ready! I am closing this issue.

**Comment by Yash-Varshney** [comment]
@malvikasharan I can't merge the P.R. as I don't have access to merging it.
