### ISSUE TITLE
Add section on setting and synching from an upstream fork

### ISSUE THREAD

**Issue by annakrystalli** [alan-turing-institute/the-turing-way#116]
Add section on setting and synching from an upstream fork to the version control chapter as discussed in https://github.com/alan-turing-institute/the-turing-way/pull/88#issuecomment-452991778

**Comment by annakrystalli** [comment]
Nice blog post about synching forks: https://robots.thoughtbot.com/keeping-a-github-fork-updated

**Comment by dingaaling** [comment]
Hello from 2022 @annakrystalli! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by the end of October we'll mark it as closed - but we are always happy to reopen it! Thank you!"

**Comment by dingaaling** [comment]
The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
