### ISSUE TITLE
Guide for Ethical Research chapter: Philosophy and Science

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1235]
## Detailed description

**captures contributions made in #913**

 * This issue is a place to discuss matters relating to the writing of the chapter on _Philosophy and Science_ within the book of _[Guide for Ethical Research](https://github.com/alan-turing-institute/the-turing-way/blob/jupyterbook-restructure/book/website/ethical-research/ethical-research.md#guide-for-ethical-research)_
* The outline of this book is specified in [pull request #913](https://github.com/alan-turing-institute/the-turing-way/pull/913)
* This chapter does not yet have a linked pull request

### Planned table of contents for this chapter

1. Motivation for reading on Philosophy of Science
1.1. Philosophy as continuous with science
1.2. The increasing specialisation of philosophical fields
2. Philosophical questions raised by the _Guide for Ethical Research_ (for example: the difference between data ethics and research ethics, and the overlap of RRI and research integrity)

#### Further subchapters:

1. Moral philosophy: intro to the concepts of:
1.1. metaethics
1.2. normative ethics
1.3. applied ethics
2. Values in science: epistemic vs. non-epistemic
2.1. Intro to feminist epistemology and the embrace of values in science
2.2. Some key values provided the discussion in 1 and the role of values outlined in 2.

### Resources

- See _[Scientific Objectivity](https://plato.stanford.edu/entries/scientific-objectivity/)_ in the Stanford Encyclopedia of Philosophy
- Please keep writing style consistent with the rest of the book (see [this issue](https://github.com/alan-turing-institute/the-turing-way/issues/1174))

### Discussion points/related issues

I enjoy a difficult philosophical question as much as the next person, but the language used and topics studied within this chapter must be accessible. Philosophy is, nonetheless, worthy of discussion within a book about ethics. What other sections might be worth including to the planned content?

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write and review chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by mloning** [comment]
The [Internet Encyclopedia of Philosophy](https://www.iep.utm.edu) is another good resource, usually a bit less technical than the Stanford Encyclopedia of Philosophy.

**Comment by Ismael-KG** [comment]
As @Chrisisour mentioned in [this discussion](https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-651731815), we could have a couple of paragraphs introducing key ethical values and principles. Maybe we could have a summary of identified values concluding the chapter. Any thoughts?

**Comment by Chrisisour** [comment]
I don't know what values we would have necessarily, but there are a few options. 

Since there are soooo many AI ethics frameworks around, some researchers have started to seek similarities among them and try to identify patterns, as well as to bring them in the wider context of applied ethics. 

**Option 1** We could have David Leslie's ethical framework from the Turing Public sector guidance [here](https://www.turing.ac.uk/sites/default/files/2019-06/understanding_artificial_intelligence_ethics_and_safety.pdf) which has two levels that we could present here:

_Level 1 - SUM Values to orient the direction of innovation_ - What should we be doing? What purpose should innovation achieve / protect?
There are four values here that I have summaries for and could provide. These are Respect, Connect, Care and Protect. 

_Level 2 - FAST Track Principles to operationalise in the flow of innovation_ - What principles do we need to abide by in practice? How do we do that?
The FAST Track principles are Fairness, Accountability, Sustainability (social and technical), and Transparency (explainability, auditability)

These principles were specifically developed in light of ML development, which isn't always what researchers do so they might not be the best in all circumstances and for all research. We might want to think about this a bit. 

**Option 2** We could use some other of the research that tries to draw parallels between different AI frameworks and identify commonalities. A good starting point would be Floridi & Cowls's paper on AI4Good from 2019 where they basically argue that all AI ethics frameworks can be summarised into the 4 traditional bioethics principles + 1 new one:
- respect for autonomy
- non-maleficence
- beneficence
- justice
- explicability - incorporating a kind of explainability, auditability, and accountability

**Option 3** We could research more into responsible research and innovation (RRI) to see what principles tend to arise there. In general, I believe the bioethics principles are often used as a starting point for such work. A good textbook on that is this [here](https://ec.europa.eu/research/science-society/document_library/pdf_06/textbook-on-ethics-report_en.pdf) 

What do you think?

**Comment by Ismael-KG** [comment]
@Chrisisour, option one sounds like something that fits really nicely under [Law and Policy](https://github.com/alan-turing-institute/the-turing-way/issues/1239) (given the last bullet point under 5.2. [here](https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-651731815)).

Option two sounds like a really interesting discussion that can fit in this chapter - ultimately, all these values (and so many more) can be questioned and even clash under different circumstances.

Option three sounds, possibly, too large in scope for this chapter? Almost like a research paper of its own?

**Comment by Ismael-KG** [comment]
Thanks for chatting today, @Sukanyashu! If I missed anything, please do share, but it sounds like we could have a section discussing specific values, such as privacy and objectivity. Could you remind me of the book you mentioned?

**Comment by sukanyashukla** [comment]
Thanks @Ismael-KG ! It was good to chat with you all too. The Book is 'Feminism Confronts Technology' by Judy Wajcman! I was specifically referring to the first chapter for some elaborate discussion on the feminist critique of technology.

**Comment by Ismael-KG** [comment]
Really nice discussion, @kushism ! It was interesting to discuss how free will seems to be limited by algorithms. There's a really interesting paper on this topic [here](https://www.researchgate.net/publication/333186032_The_Ethics_of_Algorithmic_Outsourcing_in_Everyday_Life).

**Comment by Khushism** [comment]
As per my discussion with @Ismael-KG, it could be helpful to have a section of moral philosophy briefly explaining the various approaches one could take to ethically approach the issues within data science, say privacy. And to make it more understandable, we can explore these approaches using examples or case studies. For example, a deontological explanation of why user data must be used responsibly could be found in the case of Facebook's data policies and the debated therein. 
So we can have a section on the various ways we can ethically approach data science - deontological, consequential, harm-based, rights-based, and so on, in order to set up the yardsticks of ethics against which we might evaluate the contemporary data science issues and frame policies.

**Comment by Khushism** [comment]
Considering Ethics as a repository of codes of conduct and rules of governance could be especially relevant, since the world of data science is like a virtual society, and we can argue that to have order in a society is essential. So, instead of it being an option for data scientists to consider the ethical knowledge with respect to data science policies, it could be more substantial to make the case that ethics is vast repository of knowledge that _must be_ consulted with, in order to ensure that the virtual society created by data science or algorithms of AI, remains in order.

**Comment by Chrisisour** [comment]
Hello all, sorry for being absent - been moving, etc. and not sure how much I can contribute over the next month as I settle in. 

@Khushism - this is an interesting point and an important one. Yes, we need rules to ensure order. However, we should be careful to distinguish ethics and law / regulation. Law and regulation MUST be complied with and are indeed intended to ensure order. Ethics is a branch of philosophy that specialises in helping us think through and argue about what 'good' is and how to be 'good'. What you are talking about in terms of repository of codes of conducts etc. seems to be the policy / declarations that are intended to bring some kind of consensus on the answers to these questions (what is good and how to be good). I believe that is definitely an important thing to have though, totally agree with you. It fits nicely under law and policy maybe?

**Comment by Ismael-KG** [comment]
I've come to the realisation that an important role this chapter could play is to motivate both (i) reflection on the wider Ethics Book's content, and (ii) interest in philosophy of science.

I think a possible introductory paragraph can be about philosophy as _continuous with science_ (Quine, [1995](https://www.jstor.org/stable/42970677)), mentioning the increasing specialisation of philosophical fields (philosophy of mathematics, physics, biology, psychology, economics, the social sciences, information...), but also some of the philosophical thinking inspired by scientists (for example, [Darwinism](https://plato.stanford.edu/entries/darwinism/#:~:text=Darwinism%20designates%20a%20distinctive%20form,Origin%20of%20Species%20in%201859.&text=essentialism%20about%20species%20and%20(v,and%20mode%20of%20evolutionary%20change.).

The aforementioned section on meta-, normative and applied ethics can then be a subchapter that includes a list of values like @Chrisisour suggested. And then another subchapter can reinforce the chapter about values throughout the project lifecycle by turning to ideas from feminist epistemology ([Intemann, 2010]( https://doi.org/10.1111/j.1527-2001.2010.01138.x), is a good starting point on this).

**Comment by Ismael-KG** [comment]
> Considering Ethics as a repository of codes of conduct and rules of governance could be especially relevant, since the world of data science is like a virtual society, and we can argue that to have order in a society is essential. So, instead of it being an option for data scientists to consider the ethical knowledge with respect to data science policies, it could be more substantial to **make the case that ethics is vast repository of knowledge that _must be_ consulted with**, in order to ensure that the virtual society created by data science or algorithms of AI, remains in order.

I just realised this comment by @Khushism -- or the part I have highlighted -- could be an interesting point to make **either** in the [Benefits & Challenges](https://github.com/alan-turing-institute/the-turing-way/issues/1234) chapter **or** in the section motivating research ethics in this book's [intro](https://github.com/alan-turing-institute/the-turing-way/issues/1227) **or** in this chapter if there is space to draw out a distinction between _research ethics_ and _data ethics_ (which is a question -- in part -- of analytic philosophy).

**Comment by LauraCarter** [comment]
I really like the idea of having a subchapter on values - understanding what these are and how to make them explicit. Some resources on this:
* Benjamin R, Race after Technology: Abolitionist Tools for the New Jim Code (Polity 2019)
* D’Ignazio C and Klein LF, Data Feminism (The MIT Press 2020)
* edX, ‘Data Ethics, AI and Responsible Innovation’ <https://courses.edx.org/courses/course-v1:EdinburghX+DEI01x+1T2020/course/> 
* Daniels J, Nkonde M and Mir D, ‘Advancing Racial Literacy in Tech: Why Ethics, Diversity in Hiring & Implicit Bias Trainings Aren’t Enough’ (Data & Society 2019) <https://datasociety.net/wp-content/uploads/2019/05/Racial_Literacy_Tech_Final_0522.pdf>
* Costanza-Chock S, ‘Design Justice: Towards an Intersectional Feminist Framework for Design Theory and Practice’ (Social Science Research Network 2018) SSRN Scholarly Paper ID 3189696 <https://papers.ssrn.com/abstract=3189696> accessed 18 June 2018
I think this will connect well with the proposed chapter on activism: https://github.com/alan-turing-institute/the-turing-way/issues/1575
