### ISSUE TITLE
Comms: Present project to Moz Open Leaders cohort(s)

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#126]
## Detailed description
 - So much of what we're doing is inspired by the [Mozilla Open Leadership training programme](https://mozilla.github.io/leadership-training/) that it makes sense to let them know about this project 
 - The next wave of the training programme starts on 29 Jan 2019
 - Action: Ask @acabunoc if we can let folks know about the project. For example as a quick presentation on a call? Or as a video?? Up for comments!

**Comment by acabunoc** [comment]
hey hey happy to help!

**Comment by pherterich** [comment]
@acabunoc not sure if @KirstieJane has been in touch with more details. Do you think this is of interest to a particular cohort? Then I would get in touch with the meeting hosts to ask if we can join a call to introduce the project in a few minutes.

**Comment by dingaaling** [comment]
Hello from September 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
