### ISSUE TITLE
Data analysis replications section?

### ISSUE THREAD

**Issue by acork25** [alan-turing-institute/the-turing-way#1271]
Add a section on the value of data analysis replications in the project design section of the book

I think that a section on data analysis replications might be a nice addition to the 'project design' section of the book. Data analysis replications are slightly different from reproducible research in that the code used by the initial researcher is not used in the replication – in other words, using the method description, someone writes new code to see whether the findings stick. I just watched a conference presentation ([here](https://www.dropbox.com/s/1c4myluyn7zjtrz/data_analysis_replications_ic2s2_2020.mp4?dl=0)) which suggests getting masters/undergrad students to see if they can replicate published research through writing their own code. Seemed like a really cool idea to help students get familiar with the research process earlier on. 

### What needs to be done?

- [ ] Discuss to see whether this section would fit in the book
- [ ] Complete a draft 

### Who can help?

* Anyone interested in replication analyses

---

**Comment by EstherPlomp** [comment]
Hello from 2023 @acork25 ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
