### ISSUE TITLE
External promotion pack for The Turing way

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1281]
### Summary

* This will be a resource for people who would like to represent this community in different events

### What needs to be done?

The promotion pack has been [added to the repository](https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/promotion-pack) with the following materials:
- [x] A one-page info sheet
- [x] Lightning talk
- [x] Short talk
- [x] Single slide

- FAQs: 
  - A document with FAQ has been created in the promotion pack with few initial FAQs
  - This issue will be kept open to discuss more Q&A that should be included

### Who can help?

* Anyone who potentially would like to represent the community and has a question they would like to ask or answer

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by EstherPlomp** [comment]
Hi @malvikasharan . Minor comment about the slides: I just noticed that in the last slide of the 5 min presentation the colours of the link to the twitter and scriberia artwork are not aligned with the rest of the slide/links. The slack link is not underlined.

**Comment by malvikasharan** [comment]
Thanks for the feedback @EstherPlomp. I updated the slides [here](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing).

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
