### ISSUE TITLE
Create a template for chapter issues

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#129]
## Detailed description
 - Table of contents
 - Resources
 - Discussion points/related issues

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.\ 
We recommend doing this using

---
__Update__

**Comment by r-j-arnold** [comment]
Hey @rosiehigman this is what I've used for the chapter's I'm currently writing, feel freed to use/modify/ignore as desired when addressing this issue

## Detailed description
 - This issue is a place to discuss matters relating to the writing of the chapter on *chapter_topic*.
- This chapter is being written in *pull_request_number* 
- This chapter is being developed on the *chapter_topic* branch.

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to master branch.

**Comment by rosiehigman** [comment]
Thanks @r-j-arnold, I suggest the following merged version. I can't seem to add issue templates, I think this needs to be a Turing person (@sgibson91 @LouiseABowler @KirstieJane ) unless I'm making a Github newbie mistake

## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on _chapter_topic_.
 * This chapter is being written in _pull_request_number_
 * This chapter is being developed on the _chapter_topic_ branch.
 * Table of contents
 * Resources
 * Discussion points/related issues

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 [ ] Write chapter outline
 [ ] Add material to the chapter
 [ ] Combine materials into a readable chapter
 [ ] Proofread
 [ ] Request reviews
 [ ] Address reviews
 [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by r-j-arnold** [comment]
Hi @rosiehigman,

I'm not sure Table of contents, Resources and Discussion points/related issues really *describe* the issue, so possibly they'd work better as their own subheadings?

**Comment by rosiehigman** [comment]
Good point, I've changed them to be subheadings. I think I was getting confused between detailed description of the chapter and detailed description of the issue! 🤦‍♀️

**Comment by r-j-arnold** [comment]
@rosiehigman Looks good to me, shall I close this issue?

**Comment by pherterich** [comment]
If we add this as an issue template in the .github folder, this will overwrite the one we have, right? I've just shoved this into a .md file in project management for reference which I hope is the right thing to do before closing this.
