### ISSUE TITLE
Documenting Workflows and Processes for Contributing to the Turing Way

### ISSUE THREAD

**Issue by paulowoicho** [alan-turing-institute/the-turing-way#1385]
### Summary

To help and guide contributors as they write new content (chapters, sub-chapters, personal narratives, case-studies etc.) for The Turing Way, it would be useful to have a template that not only structures their content but gives them 'pointers' to consider as they write. To develop these templates, getting insights from current and future contributors is essential. Please comment below with any "tips and tricks" you have for writing chapters for the Turing Way based on your thoughts and experiences! 

### What needs to be done?

- [ ] Please comment below with any "tips and tricks" you have for writing chapters for the Turing Way based on your thoughts and experiences! 

### Who can help?

* Anyone who has contributed or plans to contribute to The Turing Way!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
Hey @paulowoicho, one process we should capture is around translation. @tonyyzy and @annahadji have written a translation guide that is currently linked to the issues #970 #1010 #969. We would like to capture that in a chapter in the community handbook so that we can support the new contributors.

Other processes will be related to collecting case studies, personal stories, interviews, impact and so on. These can be facilitated through a series of templates that we have discussed about (in addition to the chapters and subchapters). Happy to discuss this in one of the coworking calls and start putting them together.

@KirstieJane  Can you think of other processes that should be captured?

**Comment by EstherPlomp** [comment]
Hello from 2023! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It seems that the pointer part of this issue is now available via the catch all issue: #2936

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
