### ISSUE TITLE
[BUG] Create consistencies in: Reviewing subchapters

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1422]
# Summary

- The reviewing chapter is a perfect chapter to test the checklist for consistency

## What needs to be done

- [ ] Ask @paulowoicho to provide the checklist for consistency
- [ ] test on the review chapter (has toc, uses HTML tags, etc.)

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
