### ISSUE TITLE
Create github team to make tagging folks easier!

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#143]
I'd like to have a github team (`TuringWayCoreDevs`) to make it easier to tag everyone!
The problem is that you have to be a member of the `alan-turing-institute` organisation to be on a team.

So here's my suggested steps:

- [x] Create github team: https://github.com/orgs/alan-turing-institute/teams/turingwaycoredevs
- [x] Add Turing folks to the team
  * @KirstieJane 
  * @LouiseABowler 
  * @sgibson91 
  * @martintoreilly 
- [x] Ask @martintoreilly, @triangle-man or @jamespjh to add the following people to the organisation 
  * @pherterich 
  * @alexmorley 
  * @rosiehigman 
  * @annakrystalli 
  * @r-j-arnold 
- [x] Add folks above to the team

**Comment by KirstieJane** [comment]
Hi @martintoreilly, @triangle-man or @jamespjh - any thoughts about adding the folks listed above to the Turing Institute organisation?

**Comment by pherterich** [comment]
Is this still an issue or have we found a workaround?

**Comment by jamespjh** [comment]
Oh, don't know why I didn't get notified on this in January. Apologies for dereliction of duty.

Will now add those names.

**Comment by jamespjh** [comment]
Done.

**Comment by jamespjh** [comment]
Invite will add to both org and team when accepted.

**Comment by dingaaling** [comment]
Hello from October 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
