### ISSUE TITLE
Move JupyterBook tutorial to The Carpentries format

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1433]
### Summary

* We have developed a tutorial on Jupyter Book with Turing Way for the JupyterCon, which we would like to move to the carpentries format: https://github.com/carpentries-incubator

### What needs to be done?

- [ ] Here are the notebook: https://github.com/jupytercon/2020-jupyterbook-with-turing-way
- [ ] each notebook will move an episode of the carpentries materials

### Who can help?

* @martinagvilas, @sgibson91, and @malvikasharan  
* Anyone else who would like to help doing that 💯 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by sgibson91** [comment]
I can perhaps take this on in April - and I'm also going through Carpentries instructor training next week! 🙌🏻

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan and @sgibson91! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
