### ISSUE TITLE
Revise github "good pracices"

### ISSUE THREAD

**Issue by bsipocz** [alan-turing-institute/the-turing-way#1489]
### Summary

The current version of the github workflow describes one particular workflow, with good practices listed at the bottom. This good practice, and the workflow is not exactly the practice many collaborative software project operates, and they even consider the suggestions bad practice (using merge instead of rebase, having several people working on a branch.

### What needs to be done?

- [ ] reconsider wording to be less absolute about good/bad
- [ ] detail out multiple workflows and point to examples (e.g. one smaller project where everyone has access to the main repo, vs model operating with forks and people working on their own branches

### Who can help?

---

**Comment by EstherPlomp** [comment]
Hello from 2023 @bsipocz! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
