### ISSUE TITLE
Bringing tasklists back?

### ISSUE THREAD

**Issue by wna-se** [alan-turing-institute/the-turing-way#1544]
### Summary

At the moment there are many open pull requests for converting check lists that use the [GitHub style task lists](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists) using \[ \] and \[x\] into plain bullet lists and I can't stop thinking that there should be a more ideal solution.

I have added an [Issue and pull request to update markdown-it-py to support rendering of task lists](https://github.com/executablebooks/markdown-it-py/issues/75 ). Is this a good solution?

### What needs to be done?

- [ ] What would be our ideal way of rendering the check lists?
- [ ] Is there a better way to achieve it than using the GitHub style task lists?

### Who can help?

* @malvikasharan 
* @martinagvilas 

---

**Comment by EstherPlomp** [comment]
Hello from 2023 @wna-se! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
