### ISSUE TITLE
Guide for Ethical Research chapter: Data Anonymization

### ISSUE THREAD

**Issue by irenekp** [alan-turing-institute/the-turing-way#1578]
## Detailed description

 * This issue is a place to discuss matters relating to the writing of the chapter on Data Anonymization in the Ethics Book.
 * This chapter is being written in _pull_request_number_

### Table of contents
* What is Anonymization?
* Need for Anonymization
* Considerations When Anonymizing Data
    * Understanding Your Data
    * Existing Techniques
* Re-identification Risks
    * Privacy Models
    * When to evaluate re-identification risks?
* Common misconceptions
* Anonymization Tools

### Resources
[The Anonymization Code by the Information Commissioner's Office, UK](https://ico.org.uk/media/1061/anonymisation-code.pdf) \
[IAPP Guide To Anonymization](https://iapp.org/media/pdf/resource_center/Guide_to_Anonymisation.pdf) \
[Simple Demographics Often Identify People Uniquely](https://dataprivacylab.org/projects/identifiability/paper1.pdf) \
[Privacy and data anonymization from a data scientist’s point of view](https://blog.concurlabs.com/privacy-and-data-anonymization-from-a-data-scientists-point-of-view-956226888d6b)

### Discussion points/related issues
Would any of the sections benefit from clearer names? \
Under the current structure, metrics like k-anonymization would appear as privacy models that help measure re-identification risk, would they maybe belong more to the Existing Techniques subsection instead? \
Are there any sections that seem irrelevant?
 
## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [x] Write chapter outline
 - [x] Add material to the chapter
 - [x] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by EstherPlomp** [comment]
Hello from 2023 @irenekp! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this is currently addressed in the [Data Privacy Strategy](https://the-turing-way.netlify.app/project-design/sdpm/data-privacy-strategies.html) chapter. 

As this issue is no longer being actioned, I'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
