### ISSUE TITLE
A bioinformatics case study under Guide for Reproducible Research chapter

### ISSUE THREAD

**Issue by sk-sahu** [alan-turing-institute/the-turing-way#1587]
### Summary

As a part of book-dash-nov20, I'am working on a bioinformatics case study under Guide for Reproducible Research chapter, It's still in development. Will open a PR soon to be reviewed by the community.

### What needs to be done?

- [ ] Add the notes from hackmd to appropriate `.md` file in this repo.
- [ ] Open a PR for review

### Who can help?

@malvikasharan is already helping on this. Will take the suggestion from community once it towards complete.

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by paulowoicho** [comment]
Hi @sk-sahu! Just wanted to update you that I revised the [case study template](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/templates/case-study-template). Hope it helps! Please also let me know how I can improve the template further based on insights from your work

**Comment by EstherPlomp** [comment]
Hello from 2023 @sk-sahu ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
