### ISSUE TITLE
Case study from cognitive science for Guide for Reproducible Research

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/the-turing-way#1592]
### Summary

Add a case study for [this preprint](https://psyarxiv.com/bv2pt/). Though it isn't the gold standard for reproducible science it's a good example of what can be usefully achieved by a researcher without tip-top open-software skills (e.g. no knowledge of container environments).

### What needs to be done?

[ ] drafting of case study
[ ] probably some updating of docs
[ ] PR reviewing

### Who can help?

I could do with someone to test how reproducible the analysis is without any prior experience and in a different software environment.

**Comment by malvikasharan** [comment]
@all-contributors please add @callummole for idea

**Comment by EstherPlomp** [comment]
Hello from 2023 @callummole! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
