### ISSUE TITLE
Toggle between light and dark themes

### ISSUE THREAD

**Issue by SamGuay** [alan-turing-institute/the-turing-way#1593]
### Summary

Instead of relying on a browser-based addon to get a dark mode, it'd be great to be able to toggle between a light and dark theme directly in the Jupyter book similar to what [Bookdown](https://bookdown.org/yihui/bookdown/) offers. It's been suggested upstream, directly on the jupyter-book repo (see issue [#707](https://github.com/executablebooks/jupyter-book/issues/707), but I think we could implement a quick solution in the meantime based on the person's preference on their laptop (`prefers-color-scheme` in css).

### What needs to be done?

- [ ] *Look at the structure of the CSS to verify if a quick solution is possible*
- [ ] *Change CSS accordingly*
- [ ] *Make sure accessibility standards (contrast, etc.) standards are met, and that no weird behavior happens.

### Who can help?

* Anyone interested in having a dark theme for the book!*

---

**Comment by malvikasharan** [comment]
@Hanaffi would you like to do this one? This is not a text-based task as asked by you.

**Comment by Hanaffi** [comment]
@malvikasharan Yes, Thanks

**Comment by Hanaffi** [comment]
@malvikasharan Do you have any color preferences ?

**Comment by malvikasharan** [comment]
I think you can start with a basic colour scheme to test and demo and then we can ask other members to share thoughts and preference.

**Comment by dineshkumar12004** [comment]
Hey @Hanaffi you still working on this issue ? If not can I give it a shot ?

**Comment by Hanaffi** [comment]
@dineshkumar12004 Hey, Unfortunately I'm not.
I can assign it to you. 
Good luck!

**Comment by EstherPlomp** [comment]
Hello from 2023 @@dineshkumar12004! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
