### ISSUE TITLE
get zenodo metadata right

### ISSUE THREAD

**Issue by jcolomb** [alan-turing-institute/the-turing-way#1626]
the zenodo metadata says it is a software (at least while using zotero), this probably needs to be modified.
https://zenodo.org/record/3233986#.X7vAddt7lQI

Also maybe time to update the author list ;)

I have heard the best way to get it right is to include a zenodo.json file on the code in github, but never did it myself.

**Comment by EstherPlomp** [comment]
@malvikasharan - I'm not sure if this is still showing up as software in the metadata fields and/or if we can actually change that since it is linked to GitHub releases which is usually software? 

 I think the author list issue has been addressed in the meantime (author = The Turing Way Community).

**Comment by EstherPlomp** [comment]
As mentioned above, I'll close this issue for now since it seems to be already resolved. If not, please re-open the issue!
