### ISSUE TITLE
[BUG] Book build on Netlify is failing

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#1725]
### Description

The building of the book is currently failing on CI. See #1724 for an example

#### Expected behaviour

The build succeeds and passes.

#### Actual behaviour

The build fails 😢 

### How to reproduce

Click the link posted by the netlify bot on the above PR and see the logs of the failed build.

### Your personal set up

- OS:

OSX

- Browser:

Google Chrome

- Dependencies:

**Comment by martinagvilas** [comment]
The netlify build is using `sphinxcontrib-bibtex 2.1.4` triggering [this issue](https://github.com/executablebooks/jupyter-book/issues/1137), and I guess that's why the CI from github action is not failing (its using `sphinxcontrib-bibtex 1.0.0`.

I don't understand why the netlify build is using the wrong version though, if `requirements.txt` specifies the `1.0.0` one.

**Comment by martinagvilas** [comment]
I think your branch has the old version of the `requirements.txt`, but why is the `files changed` tab on the PR not showing that difference? 😮

**Comment by sgibson91** [comment]
I git pulled before creating the branch, but maybe the action I have running to update my forks automatically didn't work. Let me git pull upstream.

**Comment by malvikasharan** [comment]
Ah, I see you have sorted this here. I also edited your file.

**Comment by sgibson91** [comment]
I synced and pushed which seems to have fixed it (but @malvikasharan also pushed a specific fix so unsure to say which)

**Comment by sgibson91** [comment]
I'll close this - thanks for your help everyone! 🚀
