### ISSUE TITLE
Delete no longer needed branches

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#177]
### Summary

There are a lot of branches that could be deleted which would tidy things up. Examples include

- alexmorley-dissemination (@alexmorley)
- ak-add_resources (@annakrystalli) 
- ph-chapterprogress (@pherterich)

### What needs to be done?

If everyone could delete any no longer needed branches they created by going to the branches tab and pressing the rubbish bin icon next to the branch names.

### Who can help?

@alexmorley @annakrystalli @KirstieJane @pherterich @rosiehigman @sgibson91

**Comment by alexmorley** [comment]
Done mine.

**Comment by KirstieJane** [comment]
I opened a PR for the last one of mine #178

**Comment by r-j-arnold** [comment]
Done and merged, so that branch is good to delete now?

**Comment by KirstieJane** [comment]
Yep! Just deleted it! Thank you ✨

**Comment by r-j-arnold** [comment]
Thanks Kirstie!

**Comment by pherterich** [comment]
Done.

**Comment by r-j-arnold** [comment]
Thanks!

**Comment by rosiehigman** [comment]
Done 🚀

**Comment by sgibson91** [comment]
I only have 2 branches and they're both currently active 👾

**Comment by sgibson91** [comment]
I'm leaving a note here on deleted branches just because I've learned some stuff today that may help out those of us who are still new to git/GitHub.

Just because you've deleted them on GitHub (using Becky's method), doesn't mean your branches are gone forever! Checking them out locally and pushing them again will revive them if you do need to for any reason.
```
git checkout <deleted-branch>
git push origin <deleted-branch>
```

However if you have deleted them remotely as well, they're still not gone forever but it's slightly more complicated to retrieve. You need an SHA (the string of random stuff generated by a commit). I've found the easiest way to find this is by finding the closed PR from the branch I want to revive and the copying the last commit made there. The command is then:
```
git checkout -b <deleted-branch> <SHA>
```

✨ 🚀

**Comment by r-j-arnold** [comment]
Nice, done!
