### ISSUE TITLE
Ideas to improve search

### ISSUE THREAD

**Issue by priyanshuone6** [alan-turing-institute/the-turing-way#1960]
Addresses #1787 

---
In the proposal, I have to think of ideas to redesign parts of the website, which mostly requires HTML and CSS. Few ideas like:
- Improving the design of the context menu by adding different coloured sections
- Adding a header and footer to the website
- Improving the design of the contents
- Advancing the search box and adding options to filter the contents (maybe using the google programmable search engine or using python, HTML)
- Showing all the contents on the right side without actually clicking them
- Adding metadata, meta description, alt text tags in HTML head to improve SEO
- Adding OG tags and Twitter cards for better link previews when the website is shared externally

And in the pull request can I add some CSS like adding different colours for headings and subheadings?

**Comment by malvikasharan** [comment]
@BatoolMM and @martinagvilas would you be able to comment on this?

**Comment by BatoolMM** [comment]
Hi @priyanshuone6, thank you for creating PR and making all these suggestions to improve the browsability of the book. Some of these ideas align with what we have in mind in terms of improving the browsability of the TW book. 

Regarding the numbering of the sections in PR #1950, I agree with @KirstieJane that it might not help much, especially if the TOC is collapsable. I also see that you had a look at the [FAIR Cookbook](https://fairplus.github.io/the-fair-cookbook/content/home.html). Another good example is [Deep learning for Molecules and Materials](https://whitead.github.io/dmol-book/intro.html#). The TOC is not collapsable in this book, and they added the alphabetical order to the chapters/guides. Also, the same TOC is added to the welcome page. This way, it seems to me that the navigation of the book, but not sure if it will apply to the TW book. We have way more sub-sections (more than 150 sub-chapters) in the TW book, and it might make the book look very overwhelming. However, I think that we need a re-do the welcome page to make it more intuitive for new users.

I like what you mentioned about improving SEO by adding metadata, meta description and advancing the search box and adding options to filter the contents. These will be **very useful** for the _Turing Way_ Book. However, am not sure about adding header/footer to the website and GO tags rignt now because our biggest priority is improving the browsability and accessibility of the book before improving its design. However, you are welcome to submit a PR for either of them and am happy to review it. 

Also, one of the ideas we had in mind (**and we are very keen to implement it**) is the **persona-based exploration** of how to navigate the book as described by @KirstieJane in [this issue in the JupyterBook](https://github.com/executablebooks/meta/issues/287#issuecomment-802878801). This includes adding clickable options to navigate different personas such as data scientists, community managers, or software engineers. In other words, adding options to make it easier to navigate the related chapters curated for the selected persona. If you have any question about it, please let me know!

Also, It will be useful to think of any of the change you are trying time add is better to be implemented in [JupyterBook codebase](https://github.com/executablebooks/jupyter-book) and then applying them in TW guide. 

**Thank you so much again**. I'll be delighted to review/help you through a PR for persona-based exploration or adding filters and advanced search option.
