### ISSUE TITLE
Notes from the Manchester Binder workshop

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#258]
### Summary

It is important to capture the lessons learned from the Binder Workshop in Manchester.

We're inviting our participants to share their experiences through the google form, but this issue is a place to capture lessons that any participant, helper or organiser want to remember 😸 

### General notes

* The workshop requires a bit of knowledge of markdown....so maybe worth sending a tutorial in the advanced email?
* The food was fab - great ordering
* The SIGNS WERE AMAAZING - thank you helpers for sending everyone the right way 😍 
* Love the postits as intro.
* Great chat during the breaks 😸 (I hope that's shared by folks feeding back too!)

### Intro talk

* I thought this was great - thank you @rosiehigman! 
* It went quite quickly, but I don't think that was problematic. (We can see what the feedback says)

### Reproducible computational environments

* I thought this talk was okaaaaay but not great (I made it 😉)
* Should have shown specific commands on capturing your environment on a local machine (eg with screenshots from VSCode rather than github screengraps). Should have had an example of conda environments.
* The cloud part needs more finessing I think, and I don't think my docker explanation was very good. I'll wait to see what the feedback says....but I definitely need to finess that section a bunch 😭 
* The paired examples exercise needs a bunch of *harmonising*.

### Paired examples

* The paired examples requires an understanding of BRANCHES on github.....which I think is super powerful but also a bit advanced. I (@KirstieJane) should have explained that much better
* I'll wait to find out what the feedback forms say, but I think the paired examples session definitely needed a bunch more specific guidelines. It was a _little_ fun to cause complete mayhem....but I suspect it wasn't as useful as I'd hoped 🤦‍♀️ 
* It was hard for people to follow the links. Needs its own markdown file in the workshops repo. Would have been a million times more useful 😞 

### Zero to Binder

* I loved @sgibson91's post it note skillz. Great having everyone take them down all together when we go to the next step
* I (Kirstie) thought this was great. Really well prepared! Thank you @sgibson91 and @betatim 💖 

### Who can help?

* @rosiehigman @sgibson91 @trallard @rainsworth @rgaiacs - please add anything you think of!
* Attendees, tell us what you think here!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by pherterich** [comment]
Pros:
* attendees made suggestions directly to binder, see https://github.com/jupyterhub/binderhub/issues/799 via @rgaiacs (thank you)

**Comment by rosiehigman** [comment]
Having an R expert is super useful and massive thanks to @trallard for answering all the questions!

**Comment by drj11** [comment]
I was an attendee.

A bit of a braindump (largely made by reviewing the published slides afterwards).

Overall it was great!

For me personally it was a good networking opportunity; renewing some relationships and meeting people who I knew from Twitter and also new people.

Good location; good food.

## On the intro talk 

https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/boost-research-reproducibility-binder/workshop-presentations/PRE_IntroBoostResReproBinder.pdf

Good introduction to Alan Turing Institute and The Turing Way.

Thought Kirstie (who I think was presenting it) was a bit
apologetic about the Code of Conduct.
Be proud of it, present it up front.
I wouldn't have attended without the CoC.

## On the Reproducible Computational Environments talk
https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/boost-research-reproducibility-binder/workshop-presentations/ReproducibleComputationalEnvironment.pdf

Good GIFs.

YAML

The "Yet another markup language" slide has exploding emoji head
with "This is actually a JSON file in the background" added as a comment.

The comment confuses the relationship between JSON and YAML.
Every JSON file is a YAML file, but not every YAML file is a JSON file.
In this particular case,
everything in this file could be replaced with JSON.
So maybe the comment should say:
"this is actually another way of writing JSON,
and could be replaced with JSON".


MRAN

You all introduce MRAN as if it is a standard thing.
Even if it is, you need to introduce it.


Small group exercise

I had cognitive overload when I tried Anna's example in this
exercise because: it was the first of the examples that I tried,
and it just so happens that I've never used R studio before.
So I was overwhelmed with questions like "where is the code",
"why are there four windows?", "what is happening in the
top-right window", "how do i make it _do_ anything?".

Because of that,
I would stress that for the first example they look at:
  - Jupyter Python people go to `binder-examples/matplotlib-versions`;
  - R people go to `annakrystalli/breaking_dplyr`;
  - command line people go to `sgibson91/CompEnv-PairedExample-1`;

and then you can try the others
including Kirstie's fiendish capstone example.

Matters of matching example to competency aside,
it is a good group exercise.
Also, shared solidarity around watching the Binder spinner.

## On the Zero to Binder workshop

This is good.

Would never have thought to click to reveal the logging pane on
the Binder launcher without this workshop.
And that's one of the best bits.

**Comment by drj11** [comment]
I have one orphan comment from my written notes taken at the time. It says: "Why are we talking about Docker?" from which I'm guessing that at the point where it appears in the computational environments talk that I thought it was a bit of a jump-cut.

**Comment by KirstieJane** [comment]
These are fab comments @drj11! Thank you! ✨ 🚀 👨‍🎤

**Comment by sgibson91** [comment]
Btw @drj11 , when it comes to building your own BinderHub in Sheffield, you could set the default editor to be `vim`! https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#set-environment-variables

**Comment by pherterich** [comment]
Same as for #316 - I would assume this will be covered in #537 and #536 and can be closed once the JOSE submission is taken care of :sparkles:
