### ISSUE TITLE
Make some fun plots based on our workshop feedback

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#273]
### Summary

We have some feedback from our first workshop in Manchester. Now we want to visualise some of it in interesting ways!

### What needs to be done?

- [ ] Make a little jupyter notebook that presents the information in [workshop_feedback_Manchester_20190301.csv](https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/boost-research-reproducibility-binder/feedback/workshop_feedback_Manchester_20190301.csv) in a beautiful and interpretable way
- [ ] You'll probably have to do a little data re-formatting, here's the google form that folks filled in to help with that step! https://goo.gl/forms/DZGFMPJ4EPClc4qK2
- [ ] Binderise it so that others can play with the report!
- [ ] Update the workshops [README](https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/README.md) file to link to that information.

### Who can help?

* I'm marking this as a `good first issue` so, core team, please leave this issue for a new contributor
* Anyone can help us make the plots! Comment here if you'd like any help 💓 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by dingaaling** [comment]
Hello from October 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
