### ISSUE TITLE
[TO EDIT] Add resource to project-design/sdpm/resources

### ISSUE THREAD

**Issue by DorienHuijser** [alan-turing-institute/the-turing-way#2884]
### Summary

Hello! I work as a research data manager for a Dutch university and I'm currently working on a project about privacy in research. As part of that project, we are creating the Data Privacy Handbook:  https://utrechtuniversity.github.io/dataprivacyhandbook/ with guidance and practical tools to handle personal data, sorted per topic. It is for now primarily aimed at researchers from our own institution, but I am convinced that much of the content is actually useful for other researchers who have to deal with the GDPR. 

Long story short: my suggestion is to add the Data Privacy Handbook to the Resources mentioned in the chapter Managing Sensitive Data Projects - if desirable of course!

### What needs to be done?

Simply add a bullet point to the resources.md file saying "[Data Privacy Handbook](https://utrechtuniversity.github.io/dataprivacyhandbook) for researchers dealing with personal data" (or something along those lines)

### Who can help?

I'd be happy to open a Pull Request myself!

### Updates

- [ ] First set of edits to chapter/subchapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by aleesteele** [comment]
Welcome to The Turing Way! We would love to have your input, @DorienHuijser! Please feel free to add links to the Data Privacy Handbook wherever you think it fits – I'm particularly thinking of the Sensitive Data sub-chapters that relate to your work. 

I will flag that we have some folks from other communities like @acocac from the [Environmental Data Science Book](https://the-environmental-ds-book.netlify.app/welcome.html) and @c-martinez from the Netherlands [eScience Centre](https://guide.esciencecenter.nl/#/) that contribute resources between their projects - maybe they could tell you more about it? Because The Turing Way is licensed CC-BY, you are totally free to add resources from The Turing Way to the Design Privacy Handbook as well. In any case, it would be great to see how we could collaborate to share best practices! 😄 

I'm the Community Manager here (but just one of many leaders in this community). If you'd like to use email to talk more about this, feel free to contact me at asteele@turing.ac.uk.

**Comment by acocac** [comment]
@DorienHuijser I'm the lead of the EDS book initiatite. The e-resource has two licenses, CC-BY to all plain content and media of the Jupyter book and MIT to interactive jupyter notebooks contributed by the community.

**Comment by c-martinez** [comment]
Hi @DorienHuijser ! From the eScience center side, we mostly contribute to chapters where research software is relevant. Of course, there is always a big overlap between software and data, so I think it is great that you are pointing to this resource!

I had a quick look a your handbook, it looks great! I'm sure it can be very useful! I did notice that you have a chapter on "pseudonymisation" marked as "Coming soon" -- I think the [LCRDM](https://www.lcrdm.nl/en/lcrdm-task-groups) task groups did some work on [anonymisation](https://zenodo.org/record/3584842#.Y4CXC3bMK3A) and pseudonymisation, so it might also be interesting to include those?

**Comment by DorienHuijser** [comment]
Hi everyone @aleesteele @acocac @c-martinez Thank you for the info and warm welcome! I will open a PR to add the Data Privacy Handbook to the Resources of the sensitive data sub-chapter. 

And indeed the LCRDM's work will definitely be included in the anonymisation/pseudonymistation chapter! (we're currently working on it)
