### ISSUE TITLE
[BUG] A colon symbol appears in the toc when it is viewed

### ISSUE THREAD

**Issue by RayStick** [alan-turing-institute/the-turing-way#2897]
# Description/Actual behaviour

_I think this is a 🐛 ?_

Just recently merged this PR - https://github.com/alan-turing-institute/the-turing-way/pull/2883
The [toc file](https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/_toc.yml#L538) says:

              - title: Data Wrangler Overview
                file: collaboration/research-infrastructure-roles/data-wrangler

Strangely, the way it shows up in the toc is like this (below) which seems to match h1 in the file itself, not what is in the _toc.yml
See the colon symbol in "Data Wranglers: Overview" which does not match the others

<img width="1008" alt="Screenshot 2022-11-28 at 12 13 32" src="https://user-images.githubusercontent.com/50215726/204276068-8448ace3-444a-45c3-b140-554b4703296b.png">

# Expected behaviour

Expected it to look like this. Even though h1 in Data Stewards has a colon, the toc display down the side does not. 

<img width="1047" alt="Screenshot 2022-11-28 at 12 13 43" src="https://user-images.githubusercontent.com/50215726/204278684-365bfd92-1805-4815-a5c6-2d3397291482.png">

**Comment by RayStick** [comment]
This is what we discussed in the co-working call @EKaroune, @aleesteele, @EstherPlomp and @harisood

**Comment by da5nsy** [comment]
This is a weird one. Thanks for flagging @RayStick.

I can reproduce this locally.
If I modify other TOC entries, they update, but if I modify this one it does not (even when I force a full rebuild with `jupyter-book build --all website`)

I'm stumped.

**Comment by sgibson91** [comment]
Hi @RayStick - This is not a bug, the title has been defined differently in two places: the `_toc.yml` file and the Markdown file. There is a colon in the title of the Markdown file created here: https://github.com/alan-turing-institute/the-turing-way/pull/2883/files#diff-5457e1a7583532adcc2da57ff2e270232267393fcef476fe2c9a5a17beef922cR2

As you pointed out with your screenshot, there is no colon in the title on the right hand side menu because that is pulling the data from the `_toc.yml` file. The main page, however, is pulling the content of the Markdown file directly.

There are two ways to achieve consistency here, either of which are acceptable:

1. Remove the colon from the title defined in the `book/website/collaboration/research-infrastructure-roles/data-wrangler.md` file, resulting in no colons anywhere, or
2. Include the colon in the title within the `_toc.yml` file by _escaping it with double quotes_, and hence having a colon in both places. So the entry should instead read the following _exactly_:
   ```yaml
   - title: "Data Wrangler: Overview"
   ```

**Comment by sgibson91** [comment]
Hang on... I'm still digging and thinking this over

**Comment by sgibson91** [comment]
Oh I see, we are seeing consistency when we are expecting none.

Tbh, if this is a bug, it's at the Jupyter Book level, rather than The Turing Way specifically

@choldgraf @damianavila do you know anything about this?

**Comment by sgibson91** [comment]
I found this in the docs, indicating that `title` should override what is in the Markdown file https://jupyterbook.org/en/stable/structure/configure.html?highlight=toc#specify-alternate-titles

**Comment by sgibson91** [comment]
related issue? https://github.com/executablebooks/jupyter-book/issues/486

**Comment by sgibson91** [comment]
I now think the following two things:

1. This is a real bug, but
2. It's probably artificially constructed, I don't think we need to be defining the `title` key in the toc entries at all, unless we _actually_ want to override something in the sidebar

**Comment by sgibson91** [comment]
PRs where we were trying to figure this out/replicate the behaviour:

- #2902 
- #2903

**Comment by RayStick** [comment]
Thanks both. I didn't quite have the right terminology to describe everything that was going on but as you see it is strange behaviour. 

Haven't looked at the PRs in detail yet but if it's helpful for me to do something on my end I'm happy to.

**Comment by da5nsy** [comment]
> In both those PRs, we cannot replicate the behaviour described by this issue (particularly in 2903 which explicitly changes another chapter that has a colon in its title) - and yet it exists. So what is different about the data wrangler overview chapter?

I disagree @sgibson91 - in #2902 this behavior **is** replicated (changing the `title:` in `_toc.yml` does **not** update the title on the lefthand TOC listing for this specific page).

The result of #2903 surprises me. And I agree there - that does **not** replicate this issue. That suggests that it is something specific to _this_ page, rather than colons in general 🤔 🤦 🤯

**Comment by sgibson91** [comment]
> I disagree @sgibson91 - in https://github.com/alan-turing-institute/the-turing-way/pull/2902 this behavior is replicated (changing the title: in _toc.yml does not update the title on the lefthand TOC listing for this specific page).

Ah, ok. Tbf, there were a few too many changes in that PR for me to track accordingly, especially since we are looking for something as tiny as whether a colon or not shows up 😬 I said in my comment over there that we saw the expected behaviour but I only checked the first change. Only now do I realise you had also changed the Data Wranglers Overview entry. Sorry.

**Comment by sgibson91** [comment]
> The result of https://github.com/alan-turing-institute/the-turing-way/pull/2903 surprises me. And I agree there - that does not replicate this issue. That suggests that it is something specific to this page, rather than colons in general 🤔 🤦 🤯

Yeah, this is way more terrifying

**Comment by sgibson91** [comment]
We should do a side by side comparison of the files for Data Wranglers Overview and the file in #2903

**Comment by sgibson91** [comment]
Another failed replication
https://github.com/alan-turing-institute/the-turing-way/pull/2905

**Comment by sgibson91** [comment]
I made the colon go away in the sidebar and the reason is _so dumb_ 😭 😭 😭 

* #2906 

<img width="741" alt="Screenshot 2022-12-02 at 16 03 53" src="https://user-images.githubusercontent.com/44771837/205334768-8108181e-080d-4ce9-ba3b-76cc11bbb42c.png">

Literally the only difference between the data wrangler file and the ML licensing file is that the ML licensing file had a blank line between the Jupyter Book reference and the h1 heading. Data Wrangler didn't and for some reason that meant that the `title` key wouldn't work?

How the files are currently:

<img width="823" alt="Screenshot 2022-12-02 at 16 05 53" src="https://user-images.githubusercontent.com/44771837/205335054-c9154c77-ff1f-4221-8f6a-baa7edb4e2ca.png">

**Comment by sgibson91** [comment]
### Is this a bug or not?

Hmmmm, depends...

A Markdown linter would complain about the current state of the Data Wranglers Overview file. The warning would be something like `must have blank lines around headers`. And it is true that in Markdown, a single line break would be rendered as a continuation of the line. A blank line renders a new paragraph. So I wonder if there's some weird parsing going on where you _actually_ end up with `(cl-infrastructure-data-wranglers)=# Data Wranglers: Overview` and that is messing something up?

That is a complete guess and I do not have enough knowledge of Jupyter Book (or sphinx) workings to validate that.

**Comment by da5nsy** [comment]
> I made the colon go away in the sidebar and the reason is _so dumb_ 😭 😭 😭
> 
>     * [[do not merge] Testing a change to data wrangler page #2906](https://github.com/alan-turing-institute/the-turing-way/pull/2906)

⚠️ Nope nope, the Data Stewards page was always performing like this (correctly).
In #2906 the preview still shows data wranglers performing incorrectly (with a colon in both the content title and TOC title, when it should only be in the content title)

**Comment by sgibson91** [comment]
Can people stop naming chapters so similarly so my brain can actually wrap itself around this? 😭 😭 😭

**Comment by sgibson91** [comment]
<img width="732" alt="Screenshot 2022-12-02 at 16 21 02" src="https://user-images.githubusercontent.com/44771837/205338120-a45cd590-b3a8-44a5-95e0-63abfa464523.png">
