### ISSUE TITLE
[Help!] Curate 10 chapters from the book for your role or area of research

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#3088]
### Summary

* We are deploying pathways for The Turing Way book users. Which means, we would be providing an entry point with curated chapters for different research roles (so that they know how to get started - rather than getting confused by 100s of chapters in the book). Find details: https://github.com/alan-turing-institute/bio-Turing-Way/blob/main/pathways/documentation.md

### What needs to be done?

- [ ] Curate 10 chapters that someone interested in your research position or domain should know
- [ ] Comment below so that we can create a pathway for your suggestion in the book this week

### Who can help?

Here are some pathways for users we would like to add in the book
* Data scientist (Novice)
* Data scientist (Advanced)
* PhD student
* Research (Software) Engineer
* Research Project Manager
* Research Community Manager
* Data Steward
* Data Manager
* Librarian
* Life scientists
* [anything else?)

---

**Comment by andreaczhang** [comment]
I can write something related to **PhD Student** 

- chapter 1: ...
- (updating)

**Comment by likeajumprope** [comment]
I can do a Research Software Engineer Chapter

**Comment by SaraVilla** [comment]
I can do Life scientist!
Which I'm also thinking might overlap with data scientist (novice)

**Comment by Susana465** [comment]
Following up on @andreaczhang suggestion, path for a PhD (in computational biology):

This is based on something I had already created for myself [here](https://github.com/Susana465/Bias-and-Reproducibility-Poster), considering bias and reproducibility at each stage of my PhD research, with wider references. But below I have done it by linking only to the Turing Way Manual, so that you can create a pathway as requested.

## 1. Design:

### 1.1. Check for bias:
 - [Identity and positionality](https://the-turing-way.netlify.app/ethical-research/self-reflection/sr-positionality.html?highlight=bias)
 - [Project Design](https://the-turing-way.netlify.app/project-design/project-design.html)
 ### 1.2. Tools for reproducibility:
 - [Version Control](https://the-turing-way.netlify.app/reproducible-research/vcs.html)
 - [Getting started with GitHub](https://the-turing-way.netlify.app/collaboration/github-novice.html)
 - [Detailed recommendations for code reuse](https://the-turing-way.netlify.app/reproducible-research/code-reuse/code-reuse-details.html?highlight=data%20analysis)
 
## 2. Data Collection:

### 2.1. Check for bias again (and always)
 - Consider [Registered reports](https://the-turing-way.netlify.app/communication/dif-articles/reg.html?highlight=harking) to avoid bias data collection and further reporting.

### 2.2. Reproducibility:
 - [Data Management Plan](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-dmp.html#rr-rdm-dmp)
 - [Keep data FAIR](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-fair.html)

## 3. Data Analysis:

### 3.1. Check for bias again (and always)
 - Do some [Self Reflection](https://the-turing-way.netlify.app/ethical-research/self-reflection/sr-prompts.html)

### 3.2. Reproducibility:
 - [Detailed recommendations for code reuse(when doing data analysis](https://the-turing-way.netlify.app/reproducible-research/code-reuse/code-reuse-details.html?highlight=data%20analysis)
 - [Data Curation](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-data-curation.html)

## 4. Reporting:

### 4.1. Check for bias again (and always)
 - Do some [Self Reflection](https://the-turing-way.netlify.app/ethical-research/self-reflection/sr-prompts.html) (again, yes, this an iterative process)
 - [Introduction to Research Ethics - positive publication bias](https://the-turing-way.netlify.app/ethical-research/ethics-intro.html?highlight=positive%20bias)

### 4.2. Reproducibility:
 - [Open Access](https://the-turing-way.netlify.app/reproducible-research/open/open-access.html)
 - [Sharing your research work](https://the-turing-way.netlify.app/project-design/pd-overview/pd-overview-sharing.html)

**Comment by malvikasharan** [comment]
@jcolomb and @johav can you please help curate chapters for the Project leaders based on the last week's workshop?
