### ISSUE TITLE
Add link to tutorial on using the command line.

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#310]
### Summary

As discussed in #259 most chapters depend on some experience of using the command line, but we don't have a resource for this.

### What needs to be done?

Find a nice tutorial on using the command line. Add it as a link in the relevant chapter's prerequisites sections.

### Who can help?

Anyone confident with the command line.

**Comment by r-j-arnold** [comment]
Maybe this one? Haven't read though but covers linux and mac https://www.taniarascia.com/how-to-use-the-command-line-for-apple-macos-and-linux/

**Comment by tomalrussell** [comment]
Maybe Software Carpentry's Unix Shell lesson? - https://swcarpentry.github.io/shell-novice/

**Comment by r-j-arnold** [comment]
Hey @tomalrussell that's a really nice one! The book part of the project's in the process of being migrated to its own repo [here](https://github.com/alan-turing-institute/the-turing-way-book). Are you happy to add the link into the prerequisites there? If not I'm fine to do it.

**Comment by srishti-nema** [comment]
Does this issue still needs work? #259 says the deadline was long back.

**Comment by jcolomb** [comment]
was about to open that issue... we should also look in the book for all [Experience with the command line](https://programminghistorian.org/en/lessons/intro-to-bash) links and replace it with a page for that.


my favourite is https://gitlab.com/slackermedia/bashcrawl ,because it is a game ! The game would gain with some ASCII art and making it a bit more straightforward in the beginning.
