### ISSUE TITLE
Notes from the Sheffield BinderHub workshop

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#336]
### Summary

This is an issue to capture some thoughts on the Sheffield Build a BinderHub workshop.

There are lots of notes in bit.ly/BinderHubShef but we can try to summarise key points here.

* **Timings**: I think the timings were good. I think a better version of the workshop would put a coffee break (or lunch) over step 6 of the zero to binderhub code-along so we aren't riffing for so long while everyone is waiting.
  * I thought the hack-your-binderhub session was a great length though - no one seemed over bored or too frustrated.
* **Food**: We forgot to track the dietary requirements from helpers and organising team members 🤦‍♀️ All saved by sequestering the vegan requirements on a separate table...but good lesson for next time!
  * Food was delicious though, and great job ordering the coffee and cakes 🍰 too!
* **Presentations**: I liked all of the presentations/demos/discussions - Great job @pherterich, @alexmorley, @sgibson91, @annakrystalli and @r-j-arnold! 
  * Good length and I think they captured everything that needed to be covered.
* **Engagement**: I didn't love the fact that there were core team members not taking part in the workshop - I think we were so panicked about needing folks to help out that we kinda forgot to reflect on the dynamic in the room when there are folks acting as though they "aren't needed".
  * Improvement for next time will be to work on more concrete trainings for and (more importantly setting expectations for the helpers - including team members.

### What needs to be done?

- [ ] Add your thoughts!

### Who can help?

* Anyone who was at the workshop!

---

### Updates

*No current updates.*

**Comment by arm61** [comment]
### My thoughts (for what they are worth) from today

#### From @KirstieJane's comments 

- **Timings**: While a coffee break at step 6 would be appealing,  it is *from experience* (repeating my comments from the workshop, blah blah drone) very difficult to tell how long the `az aks create ...` command may take so that may result in the situation of people rushing ahead in the workshop material (although this is probably desirable over today's experience of making @trallard ab lib [although she was amazing on-the-spot]) 
- **Food**: *imho* the food was sick (a positive sick), I love hummus and would never hold anyone responsible for University catering (or catering in general)
- **Presentations**: Amazing, 10/10, fantastic, seriously I wanna steal all of your slides and your timing abilities. As an audience member you held the attention and we able to explain the purpose of what you are doing clearly. Particular shout out for @sgibson91 cause living coding is bitch!
- **Engagements**: I am happy to admit that I could have done more :see_no_evil: (but cheers to the ATI for paying my hotel anyway 😉). However as an external person my role was ill/un-defined (sniff sniff scapegoat), I think there is scope for future development of this workshop that would outline the contributors' (@sgibson91, @alexmorley, @pherterich, @annakrystalli and @r-j-arnold) role versus the helpers' (@takluyver and myself) role, or maybe just roles in general. 

##### Extraneous information

@sgibson91 & @rosiehigman there is a "York Tap" too inside the train station, it must be a pub-in/near-a-train-station thing...(anyone that has information on the *location*-Tap naming for train station adjacent pubs the train spotting side of me is all ears) . 

Thank you so much for having me. As a result of "helping" I have a lot of fun ideas for contributing in the future!

**Comment by drj11** [comment]
@arm61 All the Taps love each other: https://waterlootap.com/friends

**Comment by trallard** [comment]
hey peeps!

I remember @martintoreilly or @sgibson91 (?) mentioning that the instructions to build the BinderHub on Azure would be contributed back to the main BinderHub repo.

I know that after yesterday you'll be making changes to the content but I would certainly like to add content/clarify some points. What would the best approach for this be? 
1) Create a PR here
2) Wait until the content has been added to the main repo?
3) Something else

**Comment by sgibson91** [comment]
Also, I'm sure the Binder team would really appreciate a PR to their repo. I don't currently have any open with them but happy to work with you on that.

**Comment by martintoreilly** [comment]
My default would be to fork the BinderHub docs repo to the Turing organisation, and make our changes on a branch of this fork so we can open a PR on their main repo to merge our changes.

**Comment by harisood** [comment]
Hello from autumn 2022 @KirstieJane! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
