### ISSUE TITLE
Ways to track readers of/ interactions with handbook?

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#431]
### Summary

As part of putting some impact report together, I was wondering if we want to get an understanding of how many people read the Turing Way (or parts of it). We probably wouldn't want to use a full blown third party tracker, are there any other options to get some idea of the impact the handbook might have?

**Comment by sgibson91** [comment]
@trallard has a cool way of tracking hits to certain Microsoft docs links without using e.g. Google Analytics

**Comment by KirstieJane** [comment]
Reviving this issue - although I wonder if there might be another that @paulowoicho and @malvikasharan worked on - feel free to merge if that's true.

We have a few options for analytics:

* google analytics -- no - too evil
* netlify analytics -- good because its integrated into our deployment system, too young to see if they're going to be evil too
* matomo -- good - used by a bunch of projects in the data science open source ecosystem (ROpenSci, Carpentries, Simply Secure), total ownership over the data, open source, non-evil, as complete as google analytics, uses cookies
* plausible -- good - used by a few projects in the data science open source ecosystem (scikit-image), total ownership over data, open source, non-evil, very lightweight, no cookies required

My steer would be to go with one of the open source options rather than netlify. I think that puts our money where our mouth is for supporting open source projects designed from the start to further the internet freedom movement.

I have many fewer opinions about matomo vs plausible: https://plausible.io/vs-matomo

Talking to @karthik I know Matomo allows us to see how long people spend on each page. I'm not sure if that's true of plausible.

@malvikasharan - I think its down to your choice unless anyone wades in with strong opinions!

@Arielle-Bennett - can you let me know the best way to pay for whatever service we choose? I can put it on my credit card and get reimbursed (seems easiest?!) but that might not be ok with Turing's book keeping?

**Comment by malvikasharan** [comment]
Thanks to @paulowoicho, we had merged the #1660 to test Matomo on the book (a free trial of their cloud-based analytics is over). It worked pretty well, so if we want to add Matomo, we need to set up the payment system.

look forward to hearing about other analytics system @KirstieJane mentioned and which one to take forward.

**Comment by KirstieJane** [comment]
From Thad Guirdy in the Code for Science and Society slack;

> As far as the tech stack goes, and configuration available, both Netlify and Plausible are very good.  Matomo has a bit more difficulty because of a less reactive framework that is PHP based.  Hence, if you need some custom work at some point, you'll have better luck with Netlify or Plausible.
>
> Regarding Plausible, I was very impressed last October when I questioned their Terms and Conditions and I was instantly in a nice threaded email over the course of 1 week with their CEO Marko Saric whom not only quickly fixed various documentation to improve the clarity but he and I also worked together to expand the information.  https://plausible.io/terms
>
> Needless to say, I was super impressed by Plausible's easy going and attentive leadership team whom I could actually talk to!
Plausible is super lightweight with their script being 22 times smaller than Matomo script and 45 times smaller than Google Analytics.  Also, they buy only 100% green energy to power themselves. https://plausible.io/vs-matomo

**Comment by Arielle-Bennett** [comment]
On payment - it depends on how much the overall cost is as to whether it's better to get it invoiced directly or it's fine to reimburse.  Should be resolvable either way!

**Comment by malvikasharan** [comment]
£190 +tax per year for the basic plan for Matomo.

![image](https://user-images.githubusercontent.com/5370471/109038310-82cb6480-76c3-11eb-9484-68268c487fee.png)

**Comment by malvikasharan** [comment]
@KirstieJane That's strong support for Plausible. I can test try testing it.

**Comment by paulowoicho** [comment]
Regarding user/reader experience as well, I think the fact that Plausible is more lightweight than Matomo means that it shouldn't have too much of a negative effect on the load times of pages in The Turing Way book, especially for readers on slower internet connections.

**Comment by KirstieJane** [comment]
The one thing that I know Matomo does is track how long someone is one a particular page. Netlify doesn't do that and I'm not sure about Plausible. @malvikasharan - when you're investigating can you have a look to see if Plausible gives those stats?

**Comment by malvikasharan** [comment]
@alexmorley Can you please transfer the netlify access to Kirstie and/or the turingway@gmail.com, or enable the team setting? I would like to check the analytics features directly from the Netlify server.

**Comment by alexmorley** [comment]
Verification email should be sent. Once verified I'll ping a password reset email to that address too.

**Comment by malvikasharan** [comment]
@alexmorley did you have some time to look into it?

**Comment by alexmorley** [comment]
Did you get the verification email?

**Comment by malvikasharan** [comment]
No. I didn't get it. Can you please resend this to 'theturingway@gmail.com'?

**Comment by alexmorley** [comment]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/13655521/111172480-c1a35a80-859d-11eb-9eb8-dad31d36bada.png">

should be there now

**Comment by malvikasharan** [comment]
I have added you on Keybase.

**Comment by malvikasharan** [comment]
@alexmorley can you please share your working email by emailing to theturingway@gmail.com?

**Comment by dingaaling** [comment]
Hello from 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
