### ISSUE TITLE
Auto update intro chapter with contributors snapshot

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#599]
### Summary

We take manual snapshots of the contributor section in the readme file, but it would be really convenient if the image in the book could be automatically updated when the contributor bot (via #274 ) adds a new contributor.

### What needs to be done?
Magic?

### Who can help?
Anyone with advanced skills.

**Comment by harisood** [comment]
Hello from autumn 2022 @pherterich! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
