### ISSUE TITLE
New text on Data Versioning possibly for "Reproducible Environments"

### ISSUE THREAD

**Issue by illushka** [alan-turing-institute/the-turing-way#622]
### Summary

I think it might be good to add a note about keeping track of different versions of data. Perhaps something along the lines:

> Sometimes you might want to experiment off different versions of the same dataset. And an easy way of keeping track of different combinations of the same data without having to make multiple copies is a data versioning system such as DVC (open-source Version Control System for Machine Learning Projects)  https://dvc.org/. DVC guarantees reproducibility by consistently maintaining a combination of input data, configuration, and the code that was initially used to run an experiment.

I think this text might fit in Reproducible Environments but it is hard to tell. Can someone suggest a good position for such text? 

Will also re-write in a better form once I know where it might fit.

### What needs to be done?

- [ ] *Add text to book when the ideal location is found*

### Who can help?

* Anyone

---

**Comment by jcolomb** [comment]
That is more linked to a provenance issue, right?

I think it should/will go into a "data versioning" section, as an introduction. More info on dvc might be helpful (difference with datalad)

**Comment by EstherPlomp** [comment]
Hello from 2023 @illushka, @jcolomb! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
