### ISSUE TITLE
New text suggesting a good workflow in the Version Control chapter

### ISSUE THREAD

**Issue by PranavMahajan25** [alan-turing-institute/the-turing-way#626]
### Summary 

*It would a nice idea to suggest a good workflow while working on an open source project in the version control chapter and also guide on how to keep your forked branches up to date with remote branches or master branch*

### What needs to be done?

- [ ] *Understand most commonly faced problems while keeping one's own branches up to date with remote branches*
- [ ] *Come up with a good workflow so as to avoid these issues*
- [ ] *Add relevant text at the appropriate location*

### Who can help?

* *Anyone*

---

**Comment by EstherPlomp** [comment]
Hello from 2023 @PranavMahajan25! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
