### ISSUE TITLE
Update Binder illustration by scriberia to highlight Binder infrastructure

### ISSUE THREAD

**Issue by betatim** [alan-turing-institute/the-turing-way#629]
### Summary
Create a "zoomed out" version of the drawing linked in [this thread](https://twitter.com/betatim/status/1133775417595375616). Then draw circle around the zoomed out content and add a big label "this is binder" or some such.

### Who can help?

Once the digital version of the drawing exists anyone with artistic skill can work on this. Needs a collaborator who knows about binder (maybe).

---

The title of this issue isn't very good. If someone can think of a different one please do change it.

**Comment by pherterich** [comment]
I don't really know if that's a better title now - pinging @sgibson91 as she might be able to find an artistic person at the Turing to do this.

**Comment by sgibson91** [comment]
@KirstieJane we discussed this last night

**Comment by EstherPlomp** [comment]
Hello from 2023 @betatim, @sgibson91! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
