### ISSUE TITLE
What's the best way to cite you?

### ISSUE THREAD

**Issue by orchid00** [alan-turing-institute/the-turing-way#648]
Could you provide please a way to cite you? 
I can add the whole list of contributors, but I'm not sure whether that is attached to versions of this project or other parts of the project.
Thank you

**Comment by KirstieJane** [comment]
Hi @orchid00!! I'm about halfway through uploading our different versions to Zenodo so the most correct DOI isn't yet available. But the concept DOI (10.5281/zenodo.3233853) should resolve correctly for future versions: http://doi.org/10.5281/zenodo.3233853

Do you need a particular version? And if so, by when? I can try to find time on Friday to finish uploading the different authors etc....I just need to be careful not to miss anyone out which is why I'm a little slow!

**Comment by orchid00** [comment]
Hi @KirstieJane Thanks for your feedback, I'm sure you been busy. It is not really urgent, but I would like to add you to a paper that I'm writing "10 FAIR things for imaging". Would also love for you to take a look at it. https://osf.io/zkj4r/ and review it. I'll add the newest version there.

**Comment by malvikasharan** [comment]
@KirstieJane Is there a way to cite version independent?

**Comment by KirstieJane** [comment]
Heya - you can cite all versions of the book using https://doi.org/10.5281/zenodo.3233853.

I haven't got all the different releases archived yet (😭 😩) but that general DOI will resolve to the most recent version. The DOI is great for counting citations, and if you can also include the link to the book https://the-turing-way.netlify.com that would be really amazing because it will be the most humanly readable version ✨

**Comment by jcolomb** [comment]
the zenodo metadata says it is a software, this probably needs to be modified.

**Comment by da5nsy** [comment]
There are now clear instructions on the landing page for how to cite this project.
Closing this issue 🎉
