### ISSUE TITLE
Additional resources for the code review chapter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#656]
### Summary

I'm sitting in a breakout session at [Neurohackademy](https://neurohackademy.org/) by @arokem on code review. I figured I'd make a list of useful points that we could incorporate into _The Turing Way_ 👾 

### What needs to be done?

The following bullet points are resources or pointers to be incorporated. Note that they may already be there! Fine if that's the case!

- [ ] Syncronous code review: http://fperez.org/py4science/code_reviews.html
  * A step by step guide to hosting in person code review at - for example - a lab meeting
  * Interesting that this hasn't generally taken off....maybe because scientists don't like to be reviewed?
- [ ] Find your code buddy! If having group reviews is too much, then having just one allocated person to check your code may be really valuable.
- [ ] Barriers: people don't feel like they have the ability to review....so enthusiasm often wanes very quickly.
- [ ] Maybe re-brand to "function review"!?! Note that the guidelines above do say that 50 lines is the right length....
- [ ] A blog post with guidelines that @arokem wrote: https://uwescience.github.io/neuroinformatics/2017/10/08/code-review.html
- [ ] When should code review happen? Earlier the better, but definitely before submission or presentation somewhere? Interesting that folks often give practice talks and get comments on papers...but not so much for code.
- [ ] Note that one of the biggest challenges may actually be the project planning aspect rather than the code part. So getting folks to write down _what they want to do_ in human language (not computer code) is probably a really important part.
- [ ] As a reviewer, remember to focus on what's **right** rather than just what needs to be changed. **Be Kind** 💖 
- [ ] We need some screenshots from the github interface: https://github.com/features/code-review
  * Suggest changes is a particularly positive feature - don't need to keep people guessing!
- [ ] Important to do as a group, important to watch others be reviewed. Difficult chicken and the egg problem that it's hard to know what code _should_ look like if you don't know what code should look like!!! So important to learn how to review.
  * When someone's presenting code: what is the problem, what are you trying to do, what is your criteria for success so you get useful feedback 

### Who can help?

* Anyone looking to review and add to the current code review chapter: https://the-turing-way.netlify.com/reviewing/reviewing.html is really encouraged to pick up this issue!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by sgibson91** [comment]
I love this idea. I've found even after having asynchronous review via GitHub and sharing my code on a massive screen in a meeting (brave 💪), I still get at some point "Oh, I wasn't aware your code was doing _that_". On a project where you're sharing/reusing each other's code, it's really important to understand what each part is doing and everyone's on the same page. I find in-person review is really good if your scenario is "I'm making an arbitrary decision about something and I'd like to make sure it's sensical for this universe".

**Comment by SarahAlidoost** [comment]
Thank you for making the list of points related to the code reviewing. 
I would like to incorporate in the Code reviewing process chapter some parts of [the code review chapter from eScience Center Guide](https://guide.esciencecenter.nl/#/best_practices/code_review) (I made a [draft PR](https://github.com/alan-turing-institute/the-turing-way/pull/1320)). Also, I will update the chapter based on the items mentioned here.

**Comment by SarahAlidoost** [comment]
The [PR](https://github.com/alan-turing-institute/the-turing-way/pull/1320) fixes most of the items in the top-comment of this issue. Here, a summary of where each item is implemented:
- [X] _Syncronous code review: http://fperez.org/py4science/code_reviews.html_
A link is added to section `Recommendations and best practices/Be okay with taking the discussion offline.`

- [X] _Find your code buddy!_
It is already in section `Recommendations and best practices/Keep it collaborative`
 
- [X] _Barriers: people don't feel like they have the ability to review....so enthusiasm often wanes very quickly._
Some changes are made to section `Recommendations and best practices/Who reviews?`.
 
- [X] _Maybe re-brand to "function review"!?! Note that the guidelines above do say that 50 lines is the right length...._
It is already in section `Recommendations and best practices/Review code in small chunks`
 
- [X] _A blog post with guidelines https://uwescience.github.io/neuroinformatics/2017/10/08/code-review.html_
Most of the guideline is already there.

- [X] _When should code review happen?_ 
The section `Typical workflows` will help.
 
- [X] _Note that one of the biggest challenges may actually be the project planning aspect rather than the code part. So getting folks to write down what they want to do in human language (not computer code) is probably a really important part._
Section `Checklist for code review process` will help.
 
- [X] _As a reviewer, remember to focus on what's right rather than just what needs to be changed. Be Kind_ 
It is mentioned in sections `Recommendations and best practices/Be nice!` and `Recommendations and best practices/Specify crucial versus optional changes`
 
- [X] _We need some screenshots from the github interface: https://github.com/features/code-review_
Links are added to sections `Typical workflows/Propose changes` and `Typical workflows/Create and discuss the review`

- [X] Important to do as a group, important to watch others be reviewed. 
It is already in section `Importance and personal benefits/Group knowledge and cohesion`


Some items to be considered in future improvements:
- [ ] The chapter needs more revisions providing easy to follow instructions.
- [ ] As a new topic to be incorporated into the chapter: note that the review checklist can be used to create pull request templates in GitHub. It can guide both the reviewer and coder in the review process.
