### ISSUE TITLE
Contribution Pathway: "I want to share my cool resource with The Turing Way"

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#661]
### Summary

It might be good to think of another contribution pathway for someone who has a cool repo/set of materials that they’d like to share with _The Turing Way_ and how to incorporate it without direct copy-pasting/having the materials in two places. For example, would a link out suffice? Something else? This would prevent _The Turing Way_ repo becoming large again as well, if everyone doesn’t have to include their materials here.

Suggestion from @KirstieJane:

> They'd add 1-2 paragraphs to the Turing Way that explains what the resource covers and motivates why someone would care. And then doesn't copy and paste all the materials, just links out. I think, to be really engaging, a couple of screenshots would be good as well. But the motivation and overview is the most important thing.

### What needs to be done?

- [ ] Formalise and document a pathway for contributors with ready-made materials

### Who can help?

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by harisood** [comment]
Hello from 2023 @sgibson91!  Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
