### ISSUE TITLE
Sharing/citing of codes/resources 

### ISSUE THREAD

**Issue by jonkingseestheworld** [alan-turing-institute/the-turing-way#663]
### Summary
Adding a subsection (in Credit for reproducible research) to describe why/how to share (in-progress or completed) codes/resources in a repo (e.g. github), as suggested by Kirstie in a recent Neurohack event

### What needs to be done?

- [ ] *Add information about sharing codes/resources in an open repo.*
- [ ] *Update the info to the corresponding book section.*

### Who can help?

* *I am interested in making contribution to this.*
* *anyone else interested.*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by EstherPlomp** [comment]
Hello from 2023 @jonkingseestheworld! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
