### ISSUE TITLE
Lightning talk at SciData19

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#664]
### Summary

SciData19 is a conference to promote "Better Science through Better Data".

I (@KirstieJane) am on the programme committee so I'd prefer not to speak, but I would love for someone to give a talk about The Turing Way? Anyone up for it?

https://www.springernature.com/gp/campaign/scidata-lightning-talks

### What needs to be done?

- [ ] Find someone who wants to attend SciData19 and give a talk
- [ ] Submit lightning talk proposal by 31 August 2019

### Who can help?

Anyone who wants to give a 5 min talk about the Turing Way!!

Doesn't have to be a core team member, can be someone who has contributed (eg at book dashes etc)!

---

### Updates

No updates yet.

**Comment by pherterich** [comment]
Has this been done? Will Georgia present next week or should this just be closed?

**Comment by harisood** [comment]
Hello from 2023 @KirstieJane! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
