### ISSUE TITLE
Jupyter Book update breaks CI

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#692]
### Summary

Jupyter Book has a new major release (0.6.0): https://github.com/jupyter/jupyter-book/releases/tag/v0.6.0

And it's SUPER LOVELY (I really like the download as PDF button and the footer) but it breaks our CI.

So @KirstieJane & @alexmorley have implemented a hot fix in #691 to pin to the old version of Jupyter Book....but fixing what's going wrong so we can use the 0.6 version would be better!

### What needs to be done?

- [ ] Figure out why the build is failing with the old jupyter book
- [ ] Fix that, and then fix the version of jupyter book to 0.6 in `requirements.txt`

### Who can help?

* Anyone who knows about jekyll, netlify, jupyter book and some combination of those tools. @alexmorley @emdupre and @choldgraf are already in a different thread 💖 

---

### Updates

*No updates so far*

**Comment by emdupre** [comment]
Right now I'm seeing two paths forward: 

1. either add a `jupyter-book upgrade` call to your `make site` directive, _or_ 
2. run `jupyter-book upgrade` once outside of continuous deployment and confirm that you're happy with the results, commit those, and then resume continuous deployment with jupyter book v0.6

Personally I'd lean towards the second option, since the whole-book review of any changes should only need to happen once per upgrade. But I don't know that I'd be the best person to review, in that case !

**Comment by KirstieJane** [comment]
YES - excited to close this!

**Comment by choldgraf** [comment]
thanks @martinagvilas :-)

**Comment by emdupre** [comment]
Woohoo ! 🎉✨🎉✨
