### ISSUE TITLE
Newsletter Template

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#709]
# Summary

Planning a format and mode of communication for The Turing Way Newsletters.

### What needs to be done?

- [ ] finalise sections and format.
- [ ] decide the frequency of newsletter and where to announce
- [ ] create an issue for each newsletter through which contributors can add their items for newsletters
- [ ] edit YouTube account name so the link is findable: https://www.youtube.com/channel/UCPDxZv5BMzAw0mPobCbMNuA
- [ ] add a Twitter account. For now, using the hashtag: https://twitter.com/hashtag/TuringWay?f=live
- [ ] decide an email. For now, using Kirstie's email

### Who can help?

* community members who would like to share something in the newsletter.
* community members who would like to suggest improvements/provide feedback.
* team members who are involved in communication and outreach

---

# Updates

Current sections (suggested)

## Connect with us!

- [About the project](https://www.turing.ac.uk/research/research-projects/turing-way-handbook-reproducible-data-science)
- [The Turing Way Book](https://the-turing-way.netlify.com)
- [GitHub](https://github.com/alan-turing-institute/the-turing-way)
- [Gitter](https://gitter.im/alan-turing-institute/the-turing-way)
- [YouTube Videos](https://www.youtube.com/channel/UCPDxZv5BMzAw0mPobCbMNuA)
- Twitter Hashtag [#TuringWay](https://twitter.com/hashtag/TuringWay?f=live)

You are welcome to contribute contents for the next newsletter by by
emailing the project coordinator [Kirstie Whitaker](mailto:kwhitaker@turing.ac.uk).

*Did you miss the last Newsletters? Check them [here](https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/newsletters)*.

See the next newsletter draft (Oct 2019 #713).

**Comment by KirstieJane** [comment]
Hi @malvikasharan - so sorry to be so late responding to this issue.

- [ ] The sections look good. I think it would be good to add a sentence describing each because I can't quite tell the difference between some of the sections. But I also don't really mind what the headings are so long as we let folks know what's going on!
- [ ] I'd like a monthly newsletter if you think that's do-able. It would be great for them to be predictable but I don't want to put artificial deadlines on tasks like this 😄 
- [ ] Issues for the next few newsletters sounds good.
- [ ] We can't have a custom youtube url until we have 100 subscribers....we currently have 3....that one might be a while off 😬 
- [ ] I'm sold on the use of a twitter account but I don't think I can manage it at the moment. Maybe we'll start one in January when you're full time on the project?
- [ ] Can we use the turing way gmail account (theturingway@gmail.com) as the contact email?
