### ISSUE TITLE
Update Turing webpage (autumn 2019)

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/the-turing-way#726]
### Summary

Our [Turing website](https://www.turing.ac.uk/research/research-projects/turing-way-handbook-reproducible-data-science) was last updated in April, so it's definitely time to add our latest news!

We currently have one subsection per month in the "Recent Updates" section. I'm thinking of restructuring to cut down on the number of subsections - either to spring/summer/automn/winter updates, or by topic (workshops, book updates, blog posts etc.). Opinions are very welcome; please drop me a comment below with your thoughts 😄 

### What needs to be done?

- [x] (Maybe) Restructure the "Recent Updates" section
- [x] Add links to latest newsletters
- [x] Add link to the Jupyter book
- [x] Binder updates
- [ ] Add @malvikasharan to the "Researchers" section

### Who can help?

* Anyone who has ideas! Please add your suggestions for content to this issue.
* I have edit rights on the website so I'll make the updates before the end of October.

I'm working on the updates in PR #737.

**Comment by EstherPlomp** [comment]
Hello from 2023 @LouiseABowler! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
