### ISSUE TITLE
Chapters subsections and numbers

### ISSUE THREAD

**Issue by orchid00** [alan-turing-institute/the-turing-way#732]
### Summary

Chapters that have subsections currently are ordered under a folder number. 
For example `open_research` 
`https://github.com/alan-turing-institute/the-turing-way/tree/master/book/content/open_research`
To date it has 7 subfolders.
the problem is that if a new subsection needs to be added the numbering will produce a new URL and links to previous version have risk to break.
Also it is needed to modify the TOC under folder `website` to accommodate for changes in re-structuring.

### What needs to be done?

- [ ] This needs to be consider for new additions
- [ ] A site map with the current structure should be linked to a DOI, so even if there are changes, people can go back to that version and be able to cite it.

### Who can help?

I welcome an open discussion about this.
We started the discussion with @KirstieJane on oct 30 At the collaboration cafe

**Comment by harisood** [comment]
Hello from 2023 @orchid00! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
