### ISSUE TITLE
list of DMP tools

### ISSUE THREAD

**Issue by pdurbin** [alan-turing-institute/the-turing-way#740]
### Summary

https://the-turing-way.netlify.com/rdm/rdm.html mentions DMPonline (which is awesome) but my understanding from today's discussion at https://gitter.im/alan-turing-institute/the-turing-way?at=5dbc32b314d55a3785b5a20f that there are multiple DMP tools available:

- https://dmponline.dcc.ac.uk
- https://dmptool.org
- https://argos.openaire.eu/home
- https://ds-wizard.org
- https://github.com/oblassers/dmap

### What needs to be done?

- [ ] Weave the list above into the existing text at https://the-turing-way.netlify.com/rdm/rdm.html

### Who can help?

Someone who knows something about DMP tools.

---

### Updates

None yet. Please watch this space. 😄

**Comment by jezcope** [comment]
Worth noting that DMPonline and DMPTool have recently been merged under the [DMPRoadmap project](https://github.com/DMPRoadmap/roadmap). Not sure what the current status of that work is, and it might not be relevant for the book in any case, since dmponline.dcc.ac.uk and dmptool.org are still the respective homes for the instances of the tool for UK/EU and US researchers respectively.

**Comment by sjDCC** [comment]
We started a page to list tools a while back, see: https://activedmps.org You can submit PRs to update this webpage via https://github.com/RDA-DMP-Common/activeDMPs

I did an article recently to describe different tools too http://www.data-intelligence-journal.org/p/49

**Comment by EstherPlomp** [comment]
Belated thanks for the tools list @pdurbin and the active DMP resource @sjDCC! 

I'm adding these resources via #2891
