### ISSUE TITLE
Incorporating interactive content into the Turing way documentation project

### ISSUE THREAD

**Issue by adrianbevan** [alan-turing-institute/the-turing-way#768]
Following on from a discussion with Sarah Gibson at the ATI at the start of the week, I note that I have a number of python scripts and jupyter notebooks for machine learning, that could be adapted and incorporated into this project to allow for some hands on interactive sessions.  I understand that those are lacking.

### What needs to be done?

If you're interested in exploring this please get in touch and I can head over from Mile End to the ATI to talk in person, demo what I have and if the project is interested, to understand how to get involved and contribute.

**Comment by KirstieJane** [comment]
Hi @adrianbevan!! That sounds great! Thank you so much for getting in touch ✨ 

Would you be able to attend one of the Turing Way [Collaboration Cafes](https://github.com/alan-turing-institute/the-turing-way/blob/master/project_management/online-collaboration-cafe.md)? We could chat with the community about what these contributions could look like all together?

The next one is 18 Dec at 7pm. If that's too late (we do an evening version for folks who can't contribute during their standard work day) then the next one is 15 Jan (but that's also a late one) and then the one after that will be 5 Feb at 3pm. There are more details at https://hackmd.io/@KirstieJane/CollabCafe.

If those times don't work then ping me an email (kwhitaker@turing.ac.uk) and I'm sure we can find a time to grab a coffee at the Turing in the new year 😄

**Comment by EstherPlomp** [comment]
Hello from 2023 @adrianbevan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
