### ISSUE TITLE
Promotional blurb for the Book Dash on 20-21 Feb 2020

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#782]
Here is a blurb for promoting the book dash, drafted for The carpentries newsletter:

## Application open for The Turing Way Book Dash: 20-21 February 2020
The [Turing Way](https://www.turing.ac.uk/research/research-projects/turing-way-handbook-reproducible-data-science) is hosting its first Book Dash of 2020 on 20 and 21 February 2020. Send your application by filling a [short online form](https://docs.google.com/forms/d/e/1FAIpQLSelc8XvuYfz7uIjS1H_RzaK9JI9w9Pc3IfFT4sethro-_6tlw/viewform). It is an in-person collaborative event on “how to data science” resource development, where you will work with others to add to and improve [the Turing Way book](https://github.com/alan-turing-institute/the-turing-way). The event will start on the evening of 20 February 2020 followed by the official dinner. The complete day of 21 February 2020 will be dedicated to the project content development. The skills and contributions may include, but are not limited to: science communication - skills in writing, editing and/or exciting interactive communications, great examples and case studies of reproducible research, writing new chapters, editing the current chapters and updating how the book looks online (CSS, logos, layout etc). You can read a step by step guide for the application on [this Twitter thread](https://twitter.com/kirstie_j/status/1210934696248586241).

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
