### ISSUE TITLE
Add new contributors to the project

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#795]
### Summary

Adding new contributors to the GitHub repo

### What needs to be done?

What are the criteria, i.e. how much contribution should one do to be added into the repository as a member.

- [ ] Come up with a minimum contribution
- [ ] Who should one contact to be added
- [ ] Where will their name appear (besides the contributor's page, for e.g. Zenodo?)

### Who can help?

* Kirstie
* Core members

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
