### ISSUE TITLE
[New Chapter] Reproducibility with Kedro

### ISSUE THREAD

**Issue by yetudada** [alan-turing-institute/the-turing-way#805]
## Detailed description
 * This chapter would present an alternative tool for reproducible Data Science and would introduce [Kedro](https://github.com/quantumblacklabs/kedro), a data science tool that helps data scientists apply software engineering best-practice to their workflow so that they achieve reproducible research. 
 * It would involve a walk-through example of how this is achieved, linked to the concepts presented in earlier chapters
 * We'll get to work on this one

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by EstherPlomp** [comment]
Hello from 2023 @yetudada! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
