### ISSUE TITLE
Security and safety of data

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#827]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on safe and secure data.
 * This chapter is being written in (no open PR yet)
 * This chapter is being developed on the (no designated) branch (yet).

### Resources

* The 5 safes framework https://www.ukdataservice.ac.uk/manage-data/legal-ethical/access-control/five-safes

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by HeidiSeibold** [comment]
Some ideas:

Keeping data private but make them FAIR:

- FAIR data does not have to be open (you can e.g. have a website with the meta data and allow people to apply for data access)
- LMU University hospital is planning to install a Data Use And Access Committee to organise who should get access to data
- Distributed computing infrastructure can help to keep data private at different sites but still use it for research.

Anonymisation / pseudonymisation:

- Use pseudonymisation to avoid showing names of people
- A pseudonomised data set is usually still not save to publish
- Anonymisation-Usefulness trade-off: the more anonymous the data the less useful

Simulate data:

- It can be very useful to have a simulated data set which is similar to the original data, if the original data cannot be published.

Minimum standards for working with sensitive data:

- Have the data on an encripted machine 
- Do not send data by e-mail (e-mails are like postcards for admins)
- Pseudonymise data
- Don't show the data to anyone, who is not allowed to see it (including your statistician friend and your master student)

**Comment by EstherPlomp** [comment]
Hello from 2023! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like most of your thoughts are now covered by the [Sensitive Data projects](https://the-turing-way.netlify.app/project-design/sdp.html) and [Managing Sensitive Data Projects](https://the-turing-way.netlify.app/project-design/sdpm.html) chapters!

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
