### ISSUE TITLE
Image idea for chapter on version control

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#836]
### Summary

Chapter version control could use some fun image. In my talks I use images like:

![image](https://user-images.githubusercontent.com/14146757/74824711-f09ebc80-5308-11ea-9da6-c6caac23f998.png)

*Would be nice to have an image with a desperate researcher trying to figure out which version they need to work with.*

### What needs to be done?

- [ ] *Draw image.*
- [ ] *Prepare image for online publication.*
- [ ] *Include image in chapter "version control".*
- [ ] *Create pull request.*

### Who can help?

* *Anyone who is good enough at drawing.*

---

### Updates

*None yet.*

**Comment by KirstieJane** [comment]
Could not love this more. I think the version control chapter needs something about moving from having versions you can see (as in your slide) to being saved in a “time” dimension that git allows. 

So definitely an image as you describe, but maybe an additional one describing that change of mindset for where you *find* the different versions? What do you think?

**Comment by HeidiSeibold** [comment]
Sounds good!

**Comment by HeidiSeibold** [comment]
I discussed the idea with Sam :tada: 
Excited to see what it will look like.

**Comment by EstherPlomp** [comment]
Hello from 2023 @HeidiSeibold! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
