### ISSUE TITLE
A project management file on book dash

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#847]
### Summary 

Currently, a file describing the book dash is missing. 

### What needs to be done?

- [ ] Write details
- [ ] Create a workflow for organising one
- [ ] Link to different relevant resources in the repo 
    - [ ] Previous event's report
    - [ ] Application form
    - [ ] Selection criteria for the participants

### Who can help?

* Core team
* Part contributors and members

---

### Updates

* Right now it is an empty file for test

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
