### ISSUE TITLE
Edit persona and pathway document into the TW

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#852]
##   Summary 

I want to read Rachael's content and edit it in

### What needs to be done?

- [ ] Read the existing content
- [ ] Add more personas
- [ ] Maybe create a sketch

### Who can help?

* Anyone with understanding of different level of knowledge for users

---

### Updates

None

**Comment by EstherPlomp** [comment]
Hello from 2023 @[USERNAME]]! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
