### ISSUE TITLE
New Chapter Idea: Ethics 

### ISSUE THREAD

**Issue by ArielleBL** [alan-turing-institute/the-turing-way#858]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on Ethics
 * This chapter is being written in _pull_request_number_
 * This chapter is being developed on the _chapter_topic_ branch.

### Discussion points/related issues

Nicolas: @nalessandroni 
Christina: @Chrisisour 

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
None so far

**Comment by jspickering** [comment]
I'm happy to help with this by identifying existing sections of the book that relate to Ethics and that might need either:
a) linking to this chapter
b) moving to this chapter

Would that be helpful?

**Comment by ArielleBL** [comment]
Yes, extremely helpful!

**Comment by nalessandroni** [comment]
Looking forward to contributing to this chapter! :)

**Comment by nalessandroni** [comment]
Link to HackMD where we could start gathering notes: https://hackmd.io/@nicoalessandroni/tw_ethics/edit

**Comment by EstherPlomp** [comment]
Hello from 2023! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
