### ISSUE TITLE
New chapter or section idea: project management & funding 

### ISSUE THREAD

**Issue by kdixey** [alan-turing-institute/the-turing-way#865]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on finding, applying for and managing research funding

### Table of contents
 * Finding suitable funding opportunities
 * Planning - project partners, milestones, deliverables, meetings
 * GitHub as a project management tool
 * How to work with your institution/research administrators/research managers
 * Money - explaining budgeting structures, costs that get forgotten
 * After projects 'finish': Impact, sustainability

### Resources
 * Lots of related chapters (collaborations, ethics, open data, data mangement)
 * Funding opportunity aggregators
 
## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by EstherPlomp** [comment]
Hello from 2023 @kdixey! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
