### ISSUE TITLE
Choosing software license and examples

### ISSUE THREAD

**Issue by sverhoeven** [alan-turing-institute/the-turing-way#868]
The choosing of a software license is now a link to https://choosealicense.com/. 
On the NLeSC guide there is a [document]( https://guide.esciencecenter.nl/intellectual_property_and_licensing/software_licenses.html) which explains the different types of licenses similar to https://choosealicense.com/ . We also have some [examples](https://guide.esciencecenter.nl/intellectual_property_and_licensing/examples_libraries.html) and [here](https://guide.esciencecenter.nl/intellectual_property_and_licensing/more_examples.html), how to combine software with different license types.

### Summary

We would like to add a document to the [Open source software chapter](https://the-turing-way.netlify.com/open_research/02/opensourcesoftware.html) to help you choose a software license and add a document which shows some of the difficulties choosing the right license when combining software.
The new document would replace the existing choosealicense link. The choosealicense link will be included in the new document. 

### What needs to be done?

- [x] Add [choose a license doc](https://guide.esciencecenter.nl/intellectual_property_and_licensing/software_licenses.html) from NLeSC guide to Turing Way
- [x] Add example of how licenses interact: [for libraries](https://guide.esciencecenter.nl/intellectual_property_and_licensing/examples_libraries.html) and [more examples](https://guide.esciencecenter.nl/intellectual_property_and_licensing/more_examples.html) to Turing Way
* [x] Add choose https://choosealicense.com/ to new document
* [x] Replace mentions of https://choosealicense.com/ by new document
* [x] Remove NLeSC specific way of working, by proofreading it as a non-NLeSC employee
* [x] Link to library home pages
* ~~[x] Update references.bib with things from new document~~
### Who can help?

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by c-martinez** [comment]
TODO:
* [ ] Wrap the image as a table

**Comment by LourensVeen** [comment]
Maybe there should be a bit of a discussion on whether replacing the link to ChooseALicense with this giant pile of text I wrote is actually an improvement. Reading back what I wrote years ago, I think it's actually a good explanation of what happens when you combine software from different places under different licenses, and I'm not aware of any other place where it's explained like this (including case law, a judge may disagree with this explanation actually, but that goes for any explanation currently). Still, I spent quite a lot of time on this, and it's the only point of view I've found that matches the comments and advice I've found from experts, e.g. FSF lawyers. So I think it's a potentially useful contribution to the internet.

However, most users of both the NLeSC Guide and The Turing Way will be scientists who don't care about licenses at all, but will be willing to spend five minutes putting a license on their code because someone told them they should. They're unlikely to read this whole explanation. Of course, that may mean that they'll miss a detail and do something that legal-technically doesn't work, but there's probably a lot of open source code out there about which that can be said.

Putting it in or leaving it out is both fine with me, but I think this should be discussed.

**Comment by c-martinez** [comment]
I personally think that it is nice to have a detailed explanation available -- if someone wants to read it, they can, if they don't have the time to read it, they can just click through to choosealicense and pick one in 5 seconds. Let see what reviewers of this PR think.
