### ISSUE TITLE
New chapter/section idea: naming files / folders / things

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#886]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on _chapter_topic_.
 * This chapter is being written in pull request #904 
 * This chapter is being developed on the `naming` branch.

Chapter could be based on the slide deck by @jennybc http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf
(@jennybc do you maybe know of other ressources on this?)

### Table of contents

- Why naming is important
- How to name stuff and what to avoid
   * Machine readable
   * Human readable

### Resources

http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf

### Discussion points/related issues

Is there related material already available?

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [x] Write chapter outline
 - [x] Add material to the chapter
 - [x] Combine materials into a readable chapter
 - [x] Proofread
 - [x] Request reviews
 - [x] Address reviews
 - [X] Merge to master branch.

## Updates

This is already integrated into the new book format which we will switch to after the Jupyter beta update: https://deploy-preview-977--the-turing-way.netlify.app/communication/filenaming.html

**Comment by jennybc** [comment]
Preferred location for that specific slide deck:

https://speakerdeck.com/jennybc/how-to-name-files

Where *I* actually plan to put a nicer prose version (obviously an aspirational goal):

https://rstats.wtf/how-to-name-files.html

> do you maybe know of other ressources on this?

Since these slides started circulating, I've had various conversations about them on, e.g., Twitter. I remember once being pointed to a webpage maintained by a ?university library? re: good data habits that offered a lot of overlapping advice. But I'm not sure what it was, so I'd be starting same as you re: finding other resources ... Googling it.

**Comment by HeidiSeibold** [comment]
Thank you very much @jennybc :clap: :sunflower:

**Comment by malvikasharan** [comment]
@HeidiSeibold thanks for accepting edit suggestions and merging the chapter into the repo: https://github.com/alan-turing-institute/the-turing-way/pull/904 🎉

I will keep this issue open as we still have to create a location for this chapter.

At the moment, there is a section in the research data management (rdm) chapter that briefly mentions it. Since that chapter is growing too much, we should split that into sub-chapters that will make the content be more explorable. Then we can use this chapter as one of the sub-chapters there.

We should get some input from @KirstieJane and other current contributors to the rdm chapter on how to go about splitting the chapter. here is the issue for discussion where I have recorded your chapter: https://github.com/alan-turing-institute/the-turing-way/issues/947

**Comment by HeidiSeibold** [comment]
> At the moment, there is a section in the research data management (rdm) chapter that briefly mentions it. Since the rdm chapter is growing, I have opened an issue requesting to split the chapter into sub-chapters that will make the content more explorable. Then we can use your chapter on naming as one of the sub-chapters there.

I am not sure this fits well into RDM. It is more about naming files and folders in general.

But happy to discuss :grimacing: :wink:

**Comment by malvikasharan** [comment]
I don't agree with rdm as a place for this chapter too. It could be a better fit as a sub-chapter in project management or design. Those chapters don't exist as of now, so maybe we should add this

**Comment by HeidiSeibold** [comment]
For now this seems a good idea, yes

**Comment by HeidiSeibold** [comment]
Hi @malvikasharan is there anything I can do right now to help move this into the book?

**Comment by malvikasharan** [comment]
This is already integrated into the new book format which we will switch to after the Jupyter beta update: https://deploy-preview-977--the-turing-way.netlify.app/communication/filenaming.html

Cheers!
Malvika

**Comment by HeidiSeibold** [comment]
Oh wow, thanks! :clap: 

New format is looking nice! :sunglasses:

**Comment by HeidiSeibold** [comment]
Then I guess we can close, right?

**Comment by malvikasharan** [comment]
Thanks, Heidi. I will keep it open as I wanted to make sure that nobody creates a new file naming chapter as they don't see it in the book yet. I have updated the summary now so it is clear.
