### ISSUE TITLE
Add bibliography to chapter template

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#890]
### Summary
Add bibliography to chapter template

### What needs to be done?

- [ ] Add `{% bibliography --cited %}` to https://github.com/alan-turing-institute/the-turing-way/blob/master/templates/CHAPTER_TEMPLATE.md#bibliography

### Who can help?

Anyone

---

### Updates

None yet.

**Comment by Yash-Varshney** [comment]
Hello, @HeidiSeibold  this issue seems to be completed, as there is now a sub-section `Bibliography` in the chapter template now.

**Comment by HeidiSeibold** [comment]
There is a subsection but no automatic inclusion of the citations. That would need

`{% bibliography --cited %}`

in the line below the section header.

Sorry if my issue was not clear enough. :)

**Comment by Yash-Varshney** [comment]
hey, @HeidiSeibold thanks for clarifying. 
Though, Instead of using `{% bibliography --cited %}` we can use-          
 `{% bibliography --cited_in_order %}` because, By default, the `--cited` option will still sort your bibliography if you set the sort option, whereas by using `cited_in_order` our bibliography will contain all cited items in the order they were cited on the page.
Also, as a beginner to Jekyll, can you guide me that is it okay to just add `{% bibliography --cited_in_order %}` after ##Bibliography section in the template or do I need to make more changes.

**Comment by HeidiSeibold** [comment]
I think that would be fine.

@malvikasharan what do you say?

**Comment by da5nsy** [comment]
We now have a bibliography at the end of the book: https://the-turing-way.netlify.app/afterword/bibliography.html
Style guide for reference on how to include things in the bibliography: https://the-turing-way.netlify.app/community-handbook/style/style-citing.html
