### ISSUE TITLE
Address duplicated titles issue

### ISSUE THREAD

**Issue by martinagvilas** [alan-turing-institute/the-turing-way#933]
### Summary

After the jupyter-book upgrade done in #844, an extra title using the name of the section in the side-bar was added to the top of each page in the book. Sometimes this new title is different from the old main title (e.g. [here](https://the-turing-way.netlify.com/introduction/introduction)), but sometimes it just duplicates the old main title (e.g. [here](https://the-turing-way.netlify.com/version_control/version_control.html)). 

### What needs to be done?
- [ ] We can decide to keep it this way (and close this issue)
- Or we can decide to only show the old titles
   - to achieve this, we should set this [line of code](https://github.com/alan-turing-institute/the-turing-way/blob/6dd3768b71dbc2d54396b01dd7b581bceec1f52b/book/website/_config.yml#L50) to `infer`
- Or we can change the titles in the cases where the old and the new ones are the same.

### Who can help?

Anyone can provide feedback on which of those three options would look better  ⭐️

**Comment by sgibson91** [comment]
Hi @martinagvilas! I agree with you that referring to the old titles looks better.

Screenshot for reference:

<img width="1280" alt="duplicated_titles" src="https://user-images.githubusercontent.com/44771837/77157409-329e5800-6a99-11ea-86d0-38191bae1a67.png">

**Comment by EstherPlomp** [comment]
Hello from 2023 @martinagvilas @sgibson91  ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
