### ISSUE TITLE
Turing Way for Ecology and Biodiversity Data Science in Australia

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#945]
### Summary

* Capturing different data science practices in Ecology and Biodiversity field in Australia - guided by Prof Glenda Wardle
* Potential scopes to explore: citizen science, data management, data ownership, project design, and ethics

### What needs to be done?

- [ ] Exchange contacts with the different stakeholders
- [ ] Share information about The Turing Way
- [ ] Identify topics that can be covered
- [ ] identify how to best capture their knowledge and experience in data science and best practices

### Who can help?

- TERN - Terrestrial Ecosystem Research Network, a national ecosystem observatory in Australia.
- Ecosystem Science Council ‘Making the most of data’ Working Group
- More people in the network

**Comment by malvikasharan** [comment]
A few resources from TERN:

TERN is the Terrestrial Ecosystem Research Network, a national ecosystem observatory in Australia: https://www.tern.org.au/

TERN has progressed the data description, publication, licensing and reuse in Australia, and Guru and others would have much to offer to the Turing Way project: https://www.tern.org.au/Data-publishing-pg26249.html

There are similar portals for the marine observatory IMOS: http://imos.org.au/data/
and the Atlas of Living Australia: https://www.ala.org.au/

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
