### ISSUE TITLE
Convert Zero-to-Binder tutorial into Julia

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#952]
### Summary

The [Zero-to-Binder tutorial](https://bit.ly/zero-to-binder-tutorial) is a great introduction to Binder but is biased towards using Python. A preconception that Jupyter Notebooks and/or Binder is a "Python thing" already exists and so refactoring the tutorial to work in (for example) Julia will be one step towards dispelling that. I'm hoping it will also make users who do not already know Python feel more comfortable being introduced to Binder.

### What needs to be done?

- [ ] Find an example that works with Julia
- [ ] Copy and refactor [the tutorial](https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder.md) for Julia environments
- [ ] Update the text where required
- [ ] Create new bitly link
- [ ] Create "solo" version (extra screenshots) like here: https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-solo.md

### Who can help?

* @ots22 has volunteered to help me with the Julia aspect

---

### Updates

- This is related to my SSI Fellowship: https://github.com/sgibson91/ssi-fellowship/issues/3

**Comment by ots22** [comment]
To summarize where we got to on Wednesday:
- Familiarized ourselves with the Julia package manager ([docs](https://julialang.github.io/Pkg.jl/v1/))
- Understood how to replace each step in the tutorial with an equivalent in Julia
  - Most of the steps are straightforward translations
  - Project requirements and version pinning will most likely need access to a Julia installation, to produce the files needed to describe these.
  - This seemed undesirable (particularly for when the tutorial is delivered as a hands-on workshop), since it introduces an extra prerequisite (a working Julia installation).  Perhaps not an unreasonable one though.

Related: [this issue with the Julia Binder demo](https://github.com/jupyterhub/binder/issues/189)
