### ISSUE TITLE
Remote collaboration: wellbeing of people

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#965]
### Summary 

* How to manage resources and share them across the different stakeholders when collaborating remotely

### What needs to be done?

- [ ] Collect ideas below
- [ ] Create bullet points
- [ ] Add a short descriptive list in Turing way

### Who can help?

Team members named below

**Comment by KirstieJane** [comment]
I'm going to write some paragraphs about remote coffee hours here 😄 ☕️ 👋

**Comment by malvikasharan** [comment]
@KirstieJane Should I add your text in the well-being section under the title "Creating opportunities for social interactions" or something similar (do you have a suggestion)?

**Comment by orchid00** [comment]
hi @malvikasharan here is my review of the [checklist](https://github.com/alan-turing-institute/the-turing-way/blob/ms-collaboration-book/book/content/remote_collaboration/checklist/checklist.md#checklist-for-attending-a-remote-meeting-or-event)
in response to [this tweet](https://twitter.com/MalvikaSharan/status/1242063258414198784).

These are only suggestions, pick what suits :)

- I'll add this to the "arewemeetingyet" https://www.timeanddate.com/worldclock/meeting.html
and this https://www.timeanddate.com/worldclock/fixedform.html
- to plan definitely doodle helps coordinating
- "Identify a most suitable slot that is time zone compatible for all the members " if you are planning a meeting that includes Americas/Oceania, there's definitely a need of two sessions, because not all members what to wake up in the middle of the night for a meeting. (12+ difference)
- "Distribute the shared document a few days before the meeting" I fully recommend adding this to a calendar invite so that people have it handy when needed.
- Under "Remind everyone to arrange microphone or headsets " Ask people to check their headset before the meeting.
- "Clearly share the participation guideline, code of conduct and contact information of people who can help with any issues regarding the meeting" This can be added to the document agenda item
- under "Create slides or presentation that might be needed from organiser's side (welcome, wrap up)" add contact details, date and location of resources and licence, if reusable.
- These could be merged "Explain the basic protocols for participation " and "Remind the guidelines for participating in discussions " and " For gathering opinion and response, use silent writing time rather than open discussion" On this item I'll also add have clear instructions of what's expected for writing exercises and how long it should take. I usually have a reminder in the last minute to wrap up if the exercise is 7+ minutes. 
- Start the meeting with an icebreaker question (optional) depending on how many people.  (that part probably needs to be moved up on the list)

thanks for preparing this Malvika it was great to read :)

**Comment by orchid00** [comment]
btw @malvikasharan do you want me to help with this: "Checklist for managing and participating in a distributed team" should i add some points to this issue?

**Comment by malvikasharan** [comment]
Thank you so much @orchid00 <3 I will integrate your review in the checklist.

If you have the time and capacity, I would love to have you take a lead on the distributed team section! 🙏🎉

**Comment by orchid00** [comment]
Hi Malvika,  @malvikasharan 
Checking in, how is it best to contribute? Should I make a PR with some bullet points under the section distributed team? or do you prefer that I write here in the issue?

**Comment by malvikasharan** [comment]
Hey @orchid00, please head over to this PR to add your contributions: https://github.com/alan-turing-institute/the-turing-way/pull/962

You can also comment there, but better to have your PR so that we can record your contributions fairly. This chapter will benefit so much from your perspectives. 🙌

**Comment by malvikasharan** [comment]
Added to a subchapter in the PR #1566
