### ISSUE TITLE
Translation meta-issue (read this first!)

### ISSUE THREAD

**Issue by tonyyzy** [alan-turing-institute/the-turing-way#967]
### Summary

This is the place where we will put together the stuff related to translation.

- The first discussion (where everything started) https://github.com/alan-turing-institute/the-turing-way/issues/767
- The [translation guide](https://github.com/alan-turing-institute/the-turing-way/blob/translation/translation_guide.md)
- Discussions on translation glossaries. https://github.com/alan-turing-institute/the-turing-way/issues/969
- Discussions on translation priorities. https://github.com/alan-turing-institute/the-turing-way/issues/970

---

**Comment by malvikasharan** [comment]
@mxrtinez Can you please check this one to get started?

**Comment by EstherPlomp** [comment]
Hello from 2023 @tonyyzy ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
