### ISSUE TITLE
Translation priority

### ISSUE THREAD

**Issue by tonyyzy** [alan-turing-institute/the-turing-way#970]
### Summary

Many people wonders which chapters to start first when get started on translating. We will attempt to set some priorities in this issue.

I propose to put Chapter 1 Introduction first.

### What needs to be done?

- [ ] Have a discussion on translation priorities

### Who can help?

* All translators

---

**Comment by EstherPlomp** [comment]
Hello from 2023 @tonyyzy ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
